### ISSUE TITLE
Bluetooth stuck 'on' but not able to connect anything or use airdrop

### ISSUE THREAD

**Issue by achillespilot** [baughmann/designaire-z390-intel-i9-9900k-opencore#10]
Hi Nick,

Firstly big thanks for sharing all your expertise as I definitely wouldn't have managed without! 

I've got a similar setup but using an 8086K. I was previously using Clover to boot Mojave and all was working well. I've used your EFI and brief guide to take the plunge into OC (I did start the process 'Vanilla' style but I don't have windows so when I got to the SSDT stuff I was in over my head and I stalled!) and everything seems to be working well (including a Thunderbolt 3 Apollo - I've seen that someone else was having an issue with TB). 

There seem to be 2 issues. Firstly my UAD2 PCIe is sometimes recognised and sometimes not. Could just a Catalina issue? Not sure. 

The second issue is definitely Hack related (and I'm hoping pretty simple). Bluetooth appears 'on' and the off button is greyed out, but I can't connect to any peripherals and the Hack isn't visible when airdropping from other devices. The wifi portion seems to be working fine. I'm not sure if its to do with USB mapping or if its a BT driver issue. I've got ioRegistryExplorer and I can 'see' my Broadcom card in that, if that helps to diagnose?

<img width="738" alt="Screenshot 2020-09-05 at 23 14 02" src="https://user-images.githubusercontent.com/70820477/92314271-8233fa00-efcd-11ea-8576-03875ff9465e.png">

I rarely mess with my Hackintosh, so when I do I've completely forgotten what little I know about the process! Apologies for taking even more of your time after you putting up such a straightforward guide, any hints much appreciated.

Thanks

**Comment by achillespilot** [comment]
Also just tried adding 'AirportBrcmFixup' but didn't seem to make a difference.

**Comment by achillespilot** [comment]
SOLVED - Tried quite a few things so not 100% sure that this is what did it... but when I used the SSDTs from CaseySJ's EFI and reset the NVRAM it did the trick. I'm ashamed to say I still don't understand exactly how or why! Thanks again for the guide though.

NB - the UAD2 PCIe card still seems a bit intermittent, although I think that could just be a UA driver/Catalina thing. When its not detected, the LED is solid red which according to UA is a driver issue. If there is anything Hackintosh-wise that could affect the loading of drivers for PCIe cards then it would be interesting to know.

Otherwise, thanks again for the guide!

**Comment by baughmann** [comment]
@achillespilot sorry for not responding yet :( it’s been a busy weekend haha. I’m glad to hear that it is fixed. I’ve  been meaning to integrate features from CaseySJ’s EFI but have yet to find the time :(

**Comment by achillespilot** [comment]
No problem at all! Cheers 👍🏼

On 6 Sep 2020, at 18:52, Nick Baughman <notifications@github.com> wrote:

﻿

@achillespilot<https://github.com/achillespilot> sorry for not responding yet :( it’s been a busy weekend haha. I’m glad to hear that it is fixed. I’ve been meaning to integrate features from CaseySJ’s EFI but have yet to find the time :(
