### ISSUE TITLE
Integrated WiFi/Bluetooth card does not work

### ISSUE THREAD

**Issue by LeCarlo23** [baughmann/designaire-z390-intel-i9-9900k-opencore#11]
Hi,
thank you for the share...
I have the exact same hardware (i9 9900k, Z390 Designare, Radeon VII) with you except the Wifi.
I installed Catalina following all the instructions. But once installed, my internal wifi & bluetooth card doesn't work.
A solution for that?

Thanks again

**Comment by baughmann** [comment]
Do you have the same BT/WiFi card? The Fenvi that I mentioned [in the hardware section of the read me?](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore#hardware)

**Comment by LeCarlo23** [comment]
Unfortunately i don't.

**Comment by baughmann** [comment]
Then I’m sorry man, it’s not gonna work :( the card needs to be something that there are Macintosh drivers for.

The Fenvi card is cheap and easy to install, so I’d just recommend buying that. I would also recommend buying an internal USB hub so that you can still use a water cooler if you have one, since our board only has one free internal USB slot

**Comment by achillespilot** [comment]
Hi LeCarlo, check my thread in the 'solved' bit. I used Nick's excellent guide but also some bits (SSDTs mostly) from another guide. I don't have the Fenvi card and its working for me!

**Comment by baughmann** [comment]
@achillespilot Oh that’s right I forgot that you had the same issue as well

**Comment by LeCarlo23** [comment]
@achillespilot can you share the files please?

**Comment by baughmann** [comment]
@LeCarlo23 Here is the forum post with the build guide that @achillespilot is referring to: https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/

The very bottom of the first posts contains the SSDT's that he is talking about. You just need to place the SSDTs that you need in the `EFI/OC/ACPI` folder.

**Comment by LeCarlo23** [comment]
My configuration still not work :-(

**Comment by LeCarlo23** [comment]
@achillespilot possible to share your EFI? Thx

**Comment by achillespilot** [comment]
Hi, I’m away from home at the moment sorry. I’m pretty sure it worked using the EFI from the other site. Have you tried that yet?

On 1 Oct 2020, at 18:28, LeCarlo23 <notifications@github.com> wrote:

﻿

@achillespilot<https://github.com/achillespilot> possible to share your EFI? Thx

**Comment by LeCarlo23** [comment]
Yes, but no solution... Internal wifi/bt stilt not work. I think to reinstall the all system.

**Comment by LeCarlo23** [comment]
Hello, i have reinstalled the all system, with these SDDTs from tonymacx86 and the internal intel wifi/bt still not works. Help please :-(

**Comment by baughmann** [comment]
@LeCarlo23 Have you tried the full EFI folder from that forum? 

Also you do not need to reinstall the system every time you modify the EFI folder. You just need to restart and boot to whatever drive contains the EFI partition you modified.

**Comment by LeCarlo23** [comment]
@baughmann yes, nut its still not working. Its seems also like the EFI files are not update to the last version of OC.

**Comment by baughmann** [comment]
@achillespilot I'll have to lean on you a bit more on this subject, if you don't mind. Can you send me the direct link to the EFI you're using from CaseySJ? I cannot seem to find it.

@LeCarlo23 While we wait for @achillespilot to respond so I can look into integrating the correct SSDTs into the repo, [this post](https://www.tonymacx86.com/threads/designare-z390-intel-cnvi-9560-bluetooth-partial-success.278116/) might be of interest to you.

**Comment by LeCarlo23** [comment]
https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-2420

**Comment by baughmann** [comment]
@LeCarlo23 Please link to the exact post you're talking about by copying the link via right clicking on the `#<SOME_NUMBER>` on the post, as shown in this screenshot

<img width="116" alt="Screen Shot 2020-10-03 at 11 45 31 AM" src="https://user-images.githubusercontent.com/6177411/94995702-101fe800-056e-11eb-89b7-5b4b0adaf48c.png">

**Comment by LeCarlo23** [comment]
Sorry Nick
https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/post-2157823

**Comment by baughmann** [comment]
@LeCarlo23 No worries. So that's the EFI folder you tried? I'm looking at integrate these [two](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) [drivers](https://github.com/OpenIntelWireless/itlwm) into my EFI and will let you when I finish or give up.

**Comment by LeCarlo23** [comment]
@baughmann yes... Thx a lot 👯‍♂️

**Comment by achillespilot** [comment]
Hi @LeCarlo23, when you say 'internal BT/WiFi', do you mean built in on the motherboard? Cos I don't think there is any way to get that to work. I have an external card, just not the Fenvi one. Its a Broadcom one, can't remember which. 

@baughmann - sorry I can't actually remember which parts of your EFI and which parts of Casey's I used, I also tweaked a few things myself.

Tried to upload my EFI there but Github saying max file size of 10mb... seems strange. Am I missing something? Sorry if I don't reply flat out this weekend.

**Comment by LeCarlo23** [comment]
@achillespilot in fact i do not have an external card. For the EFI folder, you can upload It to google drive.

**Comment by achillespilot** [comment]
Ah right. Sorry then, I don’t believe there’s any way to get the built in motherboard WiFi/BT to work. The chipset is incompatible with OSX as far as I’m aware.

On 3 Oct 2020, at 17:29, LeCarlo23 <notifications@github.com> wrote:

﻿

@achillespilot<https://github.com/achillespilot> in fact i do not have an external card. For the EFI folder, you can upload It to google drive.

**Comment by achillespilot** [comment]
If you google compatible cards I’m sure you can get one for cheaper than the Fenvi one.

On 3 Oct 2020, at 17:29, LeCarlo23 <notifications@github.com> wrote:

﻿

@achillespilot<https://github.com/achillespilot> in fact i do not have an external card. For the EFI folder, you can upload It to google drive.

**Comment by baughmann** [comment]
It looks like it might be possible as there are some Intel BT/ WiFi drivers in development for this card by a private individual based off of the OpenBSD drivers.

@achillespilot No worries at all man. How big is it when you compress it?

**Comment by achillespilot** [comment]
Ah right cool. That would be good if it eventually worked! 60mb compressed. Should get a chance tomorrow to try google drive although not sure if it’ll be any help now!


On 3 Oct 2020, at 17:54, Nick Baughman <notifications@github.com> wrote:

﻿

It looks like it might be possible as there are some Intel BT/ WiFi drivers in development for this card by a private individual based off of the OpenBSD drivers.

@achillespilot<https://github.com/achillespilot> No worries at all man. How big is it when you compress it?

**Comment by baughmann** [comment]
@LeCarlo23 Well I gave the Bluetooth driver a try, but it's unreliable at best.

- Device scanning is basically broken
    - I had to plug in my magic mouse/keyboard in order for them to pair)
- Handoff doesn't work

Basically, this is a non-op for me. Buy the Fenvi, it's well worth it. No point in buying a Designaire and an Intel 9900K then being reluctant to spend another $60 on a BT/WiFi card. I know it's overpriced, but it's tried and tested.

**Comment by baughmann** [comment]
Closing this as a won’t fix for now. Maybe at some point the drivers will be usable. Feel free to re-open if something changes.
