### ISSUE TITLE
AMD GPU Doesn't open JPEGs

### ISSUE THREAD

**Issue by bennydf123** [baughmann/designaire-z390-intel-i9-9900k-opencore#12]
Just wondering if there are any boot arguments or kexts that can allow opening of Jpegs without Preview crashing. Was searching around and found the boot arguement shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94 but I think that was discontinued with updates to WhateverGreen however; this still does not work.

**Comment by baughmann** [comment]
Hmm that's a new one. Can you send me one of the JPEGs you're trying to open so I can try it myself at home? I have not noticed any issues with any JPEGs I've found or produced so far.

**Comment by bennydf123** [comment]
![Uploading Screen Shot 2020-10-02 at 9.51.12 am.png…]()

**Comment by baughmann** [comment]
@bennydf123 Looks like you didn't upload the screenshot properly. Please send me the JPEGs that you're trying to open.

**Comment by baughmann** [comment]
Gonna go ahead and close this for now. If the issue persists, feel free to re-open it and upload the JPGs in question.
