### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by jfgosselin** [baughmann/designaire-z390-intel-i9-9900k-opencore#13]
First, thank you for this EFI ! Like you said I didn’t have to suffer. I was able to move from Clover to OpenCore without any issues (expect Bluetooth but I have a different brand, I’ve ordered a Fenvi just in case).

I’m wondering if you’ve looked into CaseySJ’s guide on tonymacx86. I did try that one first but no luck ... Not sure what I’ve missed, it’s the same HW. Apart from the dim keys and boot chime does it bring more features if you compare it with your EFI  ? 

https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-1165#post-2049168

**Comment by baughmann** [comment]
Thanks for your issue, I’m glad you’re having success with the EFI. I know it sucks having to buy another BT card, but a small price to pay IMO.

It’s on my list to compare and integrate for sure. However, reading thought their OpenCore post it doesn’t look like they have much extra, besides what you mentioned. However, I will need to compare the EFI folders to be sure.

[Reportedly](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/issues/8#issuecomment-674252982), my EFI has some TB3 speed issues that CaseySJ’s has solved, but I’m still not sure if this applies to the PC version or just the Clover version.

**Comment by baughmann** [comment]
@jfgosselin Upon examining the EFI folder and talking to a user of CaseySJ's, it doesn't seem like there's much major functionality missing from this my own EFI. However, when the next macOS update comes down, I'll update to OC the latest OC and try to enable the boot chime, and maybe the display brightness.

Is there a specific feature you were looking for?

**Comment by jfgosselin** [comment]
No, I was more curious to know if you could benefit from it. Thanks for looking.

**Comment by baughmann** [comment]
No worries, thank you. I'll re-open this if I find any new info.
