### ISSUE TITLE
Rear Audio Out

### ISSUE THREAD

**Issue by garaya-scad** [baughmann/designaire-z390-intel-i9-9900k-opencore#14]
I'm running a very similar hardware config: Designare z390 bios F8, Intel i9-9900K.
With the bootarg alcid=7, the headphone jack works, as does the HDMI audio output on my dGPU and even casting to Airplay speakers.
The audio out on the motherboard works, but only from the Rear Surround port (black ring) not the Line Out (green ring). Is this consistent with your experience?

I am using OC 0.5.9 with Mojave.

**Comment by baughmann** [comment]
Really? That is just bizarre... I have speakers I use from the rear [green] audio port every day.

I would try to update to the latest OC and also grab the latest AppleALC kext and Lilu for good measure. 

When you update OC you will need to update your config.plist too. You can use this website to do that: https://opencore.slowgeek.com/

**Comment by garaya-scad** [comment]
Thanks for the feedback. Will definitely update with the latest kexts. Interestingly, my config is stable despite that audio out caveat, so it's not a show stopper for me at the moment.

**Comment by baughmann** [comment]
I would highly recommend updating both the kexts AND OpenCore. Often the main kexts (WhateverGreen, AppleALC, Lilu, and VirtualSMC) are all on the same release schedule. You *may* find compatibility issues when updating them independently.

I know I had the same issue as you when I was on clover, but AppleALC and layout 7 fixed it for me.
