### ISSUE TITLE
Continuity issues

### ISSUE THREAD

**Issue by ryanpsims73** [baughmann/designaire-z390-intel-i9-9900k-opencore#15]
I have pretty much the exact same configuration as you - i9 9900k, designare, fenvi card, Radeon vii. Bluetooth and Continuity (airdrop and handoff) were working prior to the Big Sur update, and now it's not working.

I'm running opencore .6.3 and had the same kext, acpi configuration that you had and it wasn't working.

Is yours working?

**Comment by baughmann** [comment]
Yeah, my continuity and BT/WiFi is working flawlessly. Video AirPlay to my Samsung TV is pretty slow at full resolution, but that’s the only qualm I have.

You’re not using the AirportBrcm kexts, right?

**Comment by ryanpsims73** [comment]
Right, I removed that kext, and updated the plist. Ill add more details to the issue tonight to triple check.

**Comment by baughmann** [comment]
Copy that. Make sure you’re using the latest versions of all the kexts. They most major kexts get updated when OC gets updated (WhateverGreen, Lilu, AppleALC, VirtualSMC, etc)

**Comment by jahwookie** [comment]
Nick: if I up and running in Catalina on your files and advice, and it's
been running more or less perfectly for months, and managed several minor
Apple updates, what are the chances of success if I give in to the now
daily nag to do the major update to Big Sur? After a Cabin Copy backup, of
course...

**Comment by baughmann** [comment]
@jahwookie not sure man, seems to work OK for me after updating OC and Kexts, and removing AirportBrcm kexts and USBPorts. 

I would recommend you throw the latest files on a USB, and update to Big Sur. Then, overwrite the EFI on your hard drive if it works. If it doesn’t, just go back to Catalina

**Comment by jahwookie** [comment]
Thank you, Nick. Most of my audio software is definitely not ready for Big
Sur yet, but I'll give it a go when the time comes. JW

**Comment by baughmann** [comment]
@jahwookie Copy that, best of luck.

**Comment by ryanpsims73** [comment]
After re-reading the vanilla guide, I disabled USBInjectall and XhciPortLimit. Kept the USBMap enabled, and stayed with the kexts you have in the repo. The mouse and keyboard now work over bluetooth, as does continuity. I am running the latest bios, so I don't think there's an interaction between the card and the bios. Maybe there was some kind of port conflict.

**Comment by baughmann** [comment]
Hmm glad to hear you got it figured out
