### ISSUE TITLE
Bluetooth NOT Working

### ISSUE THREAD

**Issue by Z390-designhac** [baughmann/designaire-z390-intel-i9-9900k-opencore#17]
I have Fenvi FV T919 and the Bluetooth says it's on but it's not and pair let me connect .
![Screen Shot 2020-11-25 at 10 24 32 AM](https://user-images.githubusercontent.com/75035056/100255342-ff09ac80-2f08-11eb-80e9-97aed3538bb8.png)
![Screen Shot 2020-11-25 at 10 27 21 AM](https://user-images.githubusercontent.com/75035056/100255348-ffa24300-2f08-11eb-8474-750fb4e1e774.png)

**Expected behavior**
Wi-Fi works great but Bluetooth does not it shows the loading and the BlueTooth is grey out. 
**Hardware Specifications (please complete the following information):**
 - CPU: [Intel Core i7 9700K]
 - GPU: [AMD Radeon RX Vega 64 ]
 - Motherboard: [Designaire Z390]
 - Storage: [Samsung 970 Evo 1 TB APFS]
**Additional context**
using Big Sur with your EFI

**Comment by baughmann** [comment]
Have you disabled the integrated wireless chip in the BIOS?

**Comment by ryanpsims73** [comment]
Had the same problem with Erikson showing up and Broadcom not. 

After re-reading the vanilla guide, I disabled USBInjectall and XhciPortLimit. Kept the USBMap enabled, and stayed with the kexts you have in the repo. The mouse and keyboard now work over bluetooth, as does continuity. 

I didn't disable onboard wireless, and actually was able to use both at some point.

**Comment by baughmann** [comment]
@ryanpsims73 Yes that's a good point, I forgot about that. By "USBMap" I assume you mean "USBPorts.kext"?

**Comment by ryanpsims73** [comment]
Yep, sorry wasn't in front of the computer!

**Comment by baughmann** [comment]
@ryanpsims73 no worries thanks for the clarification!

**Comment by Z390-designhac** [comment]
How do you USBInjectall and XhciPortLimit?
I am new to opencore

**Comment by baughmann** [comment]
@Z390-designhac I recommend you read the OpenCore docs if you’re not familiar with how to do that. You will find them very helpful.

The gist is, you edit the ‘config.plist’ to enable/disable the kexts and ACPI patches.

**Comment by Z390-designhac** [comment]
I don't have XhciPortLimit can you send it to me

**Comment by baughmann** [comment]
@Z390-designhac my bad it looks like it’s actually a setting in your config.plist and not an ACPI patch or kext

**Comment by baughmann** [comment]
@Z390-designhac i would recommend you start by just turning off the built in chipset in the BIOS because it’s the easiest, and it’s what I’ve done, but it’s up to you.

**Comment by Z390-designhac** [comment]
How do you turn off the chipset in the bios?
Can you send pictures of setting. I am on f6 do I need to update.

**Comment by baughmann** [comment]
Yes, I would recommend updating to the latest version of the BIOS that is available on Gigabytes website

**Comment by Z390-designhac** [comment]
I updated my BIOS but it doesn't boot now

**Comment by Z390-designhac** [comment]
I downgrade the BIOS back but now it still hangs on the older bios and the fans ramp up after a little bit

**Comment by Z390-designhac** [comment]
I changed some settings in the bios and it boots up and I also disabled the Wi-Fi and everything works fine thank you for all your help I really appreciate it
