### ISSUE TITLE
Dortania is not affiliated with Acidanthera

### ISSUE THREAD

**Issue by dhinakg** [baughmann/designaire-z390-intel-i9-9900k-opencore#2]
Dortania is not affiliated with Acidanthera and our guides are not officially related to OpenCore in any way. Our guides are a community effort and are not the same as, and should be used in tandem with, the official OpenCore documentation. Please update your repo to reflect this.

**Comment by baughmann** [comment]
Thanks for the info. You learn something new every day.

I’ll update it when I can (probably today or tomorrow maybe). If you would like it updated sooner, I would be more than happy to merge it in a pull request.
