### ISSUE TITLE
Any tweak suggestions before I replace my motherboard? 

### ISSUE THREAD

**Issue by jahwookie** [baughmann/designaire-z390-intel-i9-9900k-opencore#20]
Hello - I used your Catalina EFI with great success on my Z390 i9 machine, and then updated to Big Sur, seemingly equally trouble-free, using the updated EFI. This morning I noticed slow responsiveness, and elected to restart. Ever since then, the system goes straight into BIOS. It sees all four of the hard drives, but doesn't consider any of them boot-worthy. And also will not boot from the install USB that previously worked perfectly. 

I updated the BIOS from 8 to 9i, then verified all the points you mention, also going back through the BIOS section in a detailed install tutorial by a guy named Technolli on YouTube, which had been helpful before. I'm starting to think it's a hardware thing, partly because I had been getting intermittent crackling on the Thunderbolt 3 port, which self-corrected after a shutdown interval. 

Any ideas you have for further testing would be gratefully acted upon. Thanks for all your great work and generous guidance. John W.

**Comment by baughmann** [comment]
Welcome back, @jahwookie. Yes, I'm afraid to say that's a new one.

Did you verify all of the BIOS settings *after* updating the BIOS? It's important to remember that *some* (but not all) of them get reset after upgrading. This is an issue I discovered the hard way...

It 100% sounds like a BIOS configuration issue from my experience, but I suppose there's a *small* chance that it could be hardware-related. I know that you said you went through the BIOS settings pretty extensively, and I believe you. However, we still need to troubleshoot them anyway.

I'll grab some BIOS pictures and post them here, and list off some of the big points again so we can be sure.

**Comment by jahwookie** [comment]
Pics would be very helpful. Thx again.

**Comment by baughmann** [comment]
Roger that, check back here in about 1.5 hours.

**Comment by baughmann** [comment]
@jahwookie As promised, check out the [BIOS guide](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/master/BIOS.md) that I added

**Comment by ryanpsims73** [comment]
Asking a potentially dumb question? The Bios guide says that USBPorts.kext is no longer needed for this EFI, but when I look at the config.plist, it's still set to being Enabled, and it's included in the repo. Am I missing a configuration somewhere that disables it? Does Big Sur remove some kind of port limit?

**Comment by baughmann** [comment]
@ryanpsims73 Not a stupid question at all.

You made me freak out and double-check! It's actually *disabled*
<img width="573" alt="Screen Shot 2020-12-01 at 8 20 45 PM" src="https://user-images.githubusercontent.com/6177411/100815757-b6735700-3412-11eb-86c9-43479638c2a6.png">

However, its definitely confusing if you're viewing the `config.plist` in a text editor rather than Xcode. While the format of the file may look *on the surface* to be similar to XML, it is not. IT's disabled in [this line](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/master/EFI/OC/config.plist#L346) via the `false` flag. `Enabled` is just the *key* (i.e. the *name* of the value), as seen in the screenshot above.

**Comment by ryanpsims73** [comment]
Now I see. Ok, to the second question... Does Big Sur handle the port limit differently than Catalina?

**Comment by ryanpsims73** [comment]
And thanks for clarifying that - I have mine flipped to usbinjectall false, usbports true, and onboard wifi flipped on (I run a dual boot windows machine), and everything seems to work ok. Just more curious about what Big Sur has changed to allow for inject all without any mapping.

**Comment by baughmann** [comment]
I'm really not sure. I know that there's [this issue](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#deviceproperties-injection-failing) but not if it messes USB devices.

I know that I personally have more than 17 USB devices on my system with no issue.

It may well be that `USBPorts.kext` is a *better* solution than just `USBInjectAll.kext` and I know that my system doesn't have any problems with that configuration. Maybe I will do some testing and change it. Are you using my EFI and hardware verbatim, aside from the USB kexts?

**Comment by baughmann** [comment]
@ryanpsims73 BTW I also dual boot to Windows through OpenCore, and I use the Fenvi for WiFi and BT on Windows.

Are you able to use the Fenvi on Windows alongside the integrated chip?

Do you boot to Windows via the BIOS or the OpenCore UI?

**Comment by ryanpsims73** [comment]
Boot via OpenCore UI. I was able to get both the Fenvi and Intel running at the same time with Windows, just to see how Dual Wifi would work. Overall, seems to be fine, but requires the mapping.

Not sure if you're using Thunderbolt on a monitor, but that seems to be the most finicky thing with this setup. The top thunderbolt port works fine and can drive a monitor, the bottom one not at all. Using a passthrough cable and all.

**Comment by baughmann** [comment]
@ryanpsims73 Interesting. Maybe I will go back to using the USB map. I will have to do some testing. Are you using my EFI verbatim or have you modified it?

Your issue could be related to my USB map or to my ACPI settings. Have you taken a look at either of them?

**Comment by ryanpsims73** [comment]
I'll verify. I was tinkering around with enabling, disabling kexts after I noticed stock with your EFI I couldn't use the onboard bluetooth. Rather than disable Wifi, I ended up disabling usbinject all, enabling usbports, and setting the XhciPortLimit port limit to false.

That got bluetooth and onboard wifi working at the same time. Thunderbolt on this board has always been iffy... and ACPI is a dark art.

I'll double check EFI diffs.

**Comment by baughmann** [comment]
@ryanpsims73 Ok let me know. If you’re close enough to my EFI, pull down my repo, modify it, and then make a pull request. That way you become an official contributor :)

**Comment by jahwookie** [comment]
Very detailed and complete. Thanks, NIck! I went through each slide twice
this morning, making adjustments accordingly. Still no joy — the system
refuses to recognize anything inside the box or my boot USB as bootable.
Tomorrow I'm cracking the tower open, re-seating the drives, and bridging
the CMOS reset. Then back to the BIOS with your illustrated guide. If that
doesn't work, time for a new mobo. But your illustrations will be just as
useful at that point! Will update...

**Comment by baughmann** [comment]
Well that sucks. OK, let me know what you end up doing. Just a weird issue though....

**Comment by baughmann** [comment]
@jahwookie so, what’s the word?

**Comment by jahwookie** [comment]
Yeah, it seems this board is the equivalent of paralyzed from the neck
down: knows it has toes, but can't make them wiggle. I usually update some
components once a year anyway, so the refresh is a little early this time.
Will be glad to see the back of 2020! This will take into next week.. will
post results. Good weekend, all!

**Comment by baughmann** [comment]
Well, that blows...

Are you gonna get the same exact board? If so, double check that its revision 1. If it's anything else, IDK what will be different. IDK if they even have multiple hardware revisions.

**Comment by jahwookie** [comment]
The one I'm replacing is the Z390 Aorus Xtreme. Planning to replace with
your Designaire, and I'll make sure it's Rev. 1 or better. Thanks.

**Comment by jahwookie** [comment]
Update, early Sunday -

Well, before trashing the existing mobo, thought I'd give it a test shot
with a bootable Windows 10 USB I had lying around. The process was annoying
and very much on the pushy, upsell side, but it worked, easily, including
soft and hard restarts.

So, I redid the OS 11 flash drive, and somehow it was acknowledged this
time, and allowed me to do an install. At that point I erased the drive
where I'd put Windows, though in the BIOS it took a re-flash of 9i followed
by a flash of 8 to get rid of the Windows boot residue that kept showing up
as bootable, even though it had no OS to trigger. Ultimately, I did
installs of Big Sur on both of the SATA drives that show up in BIOS, but
NOT as bootable. And I can get to either of them, but ONLY as long as I
keep the boot USB in a slot. Suppose I could go on like that, but it isn't
making me confident enough to spend half a day installing software etc.

I ran Repair from Recovery on both drives, with no effect. I've also
ordered an NvME drive, and will ghost one of the installations over to it
early next week, and see if that's any different. Clearly, I'm not an old
hand at any of this, so let me ask a question to determine if I'm doing
something wrong on a basic level:
I made the install Big Sur USB using the Apple approved method, with an
install file downloaded from the App Store, and copied in with the Terminal
command they provide online. Then, I mount the factory file's EFI folder
using Clover Configuration, and copy in your EFI. Is that the correct
method so far? Is there anything else I should be adding, or some
additional process I"m skipping? I mean, it works, but thought I'd ask.

Any ideas at all for things to try, either in the BIOS or Configurator,
would be most welcome.

Thanks, and have a good Sunday. John W.

**Comment by jahwookie** [comment]
LInk to some snapshots that illustrate current state of high functioning
not-quite-right-ness.

https://photos.app.goo.gl/CWuZSCrrLaskFUw38

**Comment by baughmann** [comment]
@jahwookie IDK how I missed this in my inbox, sorry for the delayed response.

That's fantastic news! I don't know how any of the Windows crap managed to get left over after wiping the drives. What did you use to erase the drives? The Win 10 install USB?

And yes, you *are* indeed missing a critical step. You need to do the same thing to the macOS HDD that you did to the macOS install USB: You need to put my EFI on there.

Basically:

1. Boot to macOS using your USB
2. Use `diskutil list` to find the drive that looks like this:
<img width="639" alt="Screen Shot 2020-12-06 at 2 17 13 PM" src="https://user-images.githubusercontent.com/6177411/101289998-c5b92280-37cd-11eb-851b-4cc92c7d4820.png">
3. Use `sudo mkdir /Volumes/EFI` to make a mount point for the partition, then mount it with `sudo mount -t msdos /dev/disk0s1` (note, it's `disk0s1` in the screenshot, but your identifier may be different). You can also use Clover configurator if you'd prefer.
4. Delete any folders currently on that drive, then empty the trash (just right-click on the trash can on the dock and hit "Empty", this empties your main trash as well as the trash folders on any mounted drives)
5. Copy my EFI (or the one you made yourself on the USB) over to this folder
6. Enjoy

**Comment by jahwookie** [comment]
Aha! Thanks so much. I'll report back on this by tmrw. Have a good evening!

**Comment by jahwookie** [comment]
That totally worked. You're a lifesaver, several times over. This treatment
is only really necessary for the boot drive, I assume, yes? Anyway, thanks
again! John W.

Now, we just need to keep eyes and ears open for when the schematic for the
Apple silicon chips leaks sometime in the next year or two, and one of the
less scrupulous Asian firms starts cloning them for retail sales in the
West!

**Comment by baughmann** [comment]
Good to hear! And yes, only for the macOS boot drive.

I'm not sure I'd trust a processor like that hahah.
