### ISSUE TITLE
Thunderbolt hot-plug not working

### ISSUE THREAD

**Issue by ookerberry** [baughmann/designaire-z390-intel-i9-9900k-opencore#21]
Great config & mini guide.  Thanks for taking the time to create this!

Did you have to do anything special (like ROM updates on the motherboard) to get Thunderbolt hot-plug to work on the Z390 Designare?  It's not working for me--do you have any suggestions to resolve this/get to the bottom of it?

**Comment by baughmann** [comment]
Hmm, no I didn't.

I neglected to ensure that hot swap still works on the latest EFI and Big Sur. I will double check when I get home later.

**Comment by ookerberry** [comment]
Also, have you patched your TB3 ROM or is it still the stock ROM?

**Comment by baughmann** [comment]
I haven't patched the ROM at all. The only think I've done to any of the board firmware is update the BIOS, but that's it.

**Comment by ookerberry** [comment]
I patched my TB3 ROM (I believe this is problematic if you dual-boot windows or linux--but it is fantastic if you just use macOS):
https://www.chucknemeth.com/usb-devices/ch341a/3v-ch341a-mod
https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-1640#post-2087524

and added SSDTs:
https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-1640#post-2087524

Everything works perfectly--I wish I had done the TB3 ROM hack earlier
