### ISSUE TITLE
Almost same Build except for GPU

### ISSUE THREAD

**Issue by riyas1980** [baughmann/designaire-z390-intel-i9-9900k-opencore#22]
Hi,

First of all, thanks for EFI. Actually I almost have the same build as yours. Except for GPU and SSD

CPU | Intel Core i9 9900K
MB | Gigabyte Designaire Z390
GPU | Sapphire PULSE RADEON RX 5600 XT
SSD | PNY XLR8 CS3030 M.2 NVMe (NVMe - 500GBB)
BT/Wi-Fi | Fenvi T919 Bluetooth/Wi-Fi Card

For SSD, I don't think that there will be any issue. But for GPU, do you know if I need to change anything ?

Sorry, I am not an expert. I just want your opinion.

Thanks again.

**Comment by baughmann** [comment]
You may very well have to, but I cannot be sure. You might try taking a look [at the docs](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#gpu-support) and [this Reddit post](https://www.reddit.com/r/hackintosh/comments/ew9do2/any_success_with_5600xt/fgtqetm?utm_source=share&utm_medium=web2x&context=3)

**Comment by riyas1980** [comment]
Thanks a lot. I am gonna check it.

**Comment by baughmann** [comment]
No worries. Give it a try and let me know.

**Comment by riyas1980** [comment]
I am waiting for my GPU card to be delivered. Once I receive it, I will try and keep you informed. Thanks again for your help

**Comment by baughmann** [comment]
Wait, you bought a different one? Which one, and why?

**Comment by riyas1980** [comment]
No no. Actually I am building a new PC for Hackintosh. Received evertything except my GPU (Sapphire PULSE RADEON RX 5600 XT). So waiting for it to try :-)

**Comment by baughmann** [comment]
Ahh makes sense. Best of luck!

**Comment by baughmann** [comment]
Closing this for now, re-open if you have issues. Good luck!
