### ISSUE TITLE
Include BIOS in the repo

### ISSUE THREAD

**Issue by hellojere** [baughmann/designaire-z390-intel-i9-9900k-opencore#24]
As Gigabyte motherboards allow to import and export BIOS using a FAT32 formatted USB drive, wouldn't it be best to include the correct BIOS in the repo as well? 

I'm currently using a BIOS with Clover that was provided in a similar matter. The process is described in method #1 on this video: https://www.youtube.com/watch?v=ze4Dg11W3hU

I'm about to upgrade my system in the coming days, so in case a BIOS cannot be provided, I can try to follow the recommended BIOS settings and include it in the repo, but an original would obviously be the best. 

Or am I missing something here?

**Comment by baughmann** [comment]
That’s a valid point.

However I have one concerns, but maybe it’s not a big deal. Let me know what you think, or if I’m misunderstanding you.

The BIOS file needs to be put on the primary partition of the USB, while the EFI folder needs to be put on the EFI partition... I*think*... I would need to include instructions specifying this. I also don’t think that it’s possible to put it on a primary partition containing a bootable OS (like the macOS installer).

If it *can* be put on the EFI, my only concern then is eating up too much space on the EFI partition. If someone deletes multiple EFI folders from it without reformatting the drive, then they will need to empty the trash before putting more stuff on the EFI partition. It’s not super-evident how to do this in Mac so people may get confused.

Or, are you talking about another method altogether?

What do you think?

Also, what’s your motivation for this? Are you unable to access Gigabyte’s website?

**Comment by hellojere** [comment]
This would have nothing to do with EFI, so one would have to create another USB drive for it.

The motivation is strictly to make it as simple as possible for everyone to get things running. 

I'm able to access Gigabyte's website, but that has the default BIOS presets. One is able to export and save a Unix executable file from the BIOS that can be then later on imported back to the motherboard. This includes all the custom presets as well and is around 10 KB in size. 

This should allow people to simply create a FAT32 formatted drive, place the Unix executable there, import it in the BIOS, and then start the installing process of macOS straightaway. 

In general, it's been great to have a backup of the BIOS presets e.g. when upgrading the BIOS version goes wonky, so even if you don't see it fitting in the repo, I would recommend keeping one yourself.

**Comment by hellojere** [comment]
Actually, I'm not sure if the BIOS export includes only the custom presets or both presets and the correct BIOS version, but nevertheless, I can see it being pretty helpful compared to everyone going through the BIOS settings themselves.

**Comment by baughmann** [comment]
Ahhhh I see you're talking about the BIOS *configuration* that makes sense. That's a good idea! I thought the video you sent me was talking about the firmware update.

**Comment by baughmann** [comment]
Let me investigate and get back to this thread later.

**Comment by baughmann** [comment]
I've put the BIOS configuration [here, as a release](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/releases/tag/BIOS_Conf_F9i). Unfortunately, I cannot update the README and BIOS instruction files for another 6 hours or so, unless you could do me a solid and make the changes in a PR?

**Comment by baughmann** [comment]
@hellojere see #26 As to why this is not possible :(

**Comment by hellojere** [comment]
@baughmann Thanks for trying that out. Weird, as I've successfully used this on my system. The filesize was significantly smaller though, being around 10KB whilst yours was 10MB. 

As soon as I find some time from work to migrate to this EFI, I'll have a look at this as well. 

Thanks again, and sorry for the trouble.

**Comment by baughmann** [comment]
No worries, it’s a good idea if we can make it work

**Comment by hellojere** [comment]
Currently trying to upgrade here (facing some issues, but that's another topic 😅) and just got through the BIOS update and configuration. 

Indeed it's not the BIOS itself I meant here, but rather the configuration profile. Those can be saved and loaded to an external USB as well as slots on the Motherboard itself - to my understanding these work just fine on every motherboard. 

![IMG_0080](https://user-images.githubusercontent.com/773501/101775595-63775f00-3af8-11eb-9894-02fc58fad24c.jpg)

**Comment by baughmann** [comment]
Ahh well duh I guess that makes sense haha. Wait one and I'll post it here.

**Comment by baughmann** [comment]
@hellojere Try this one. the file size looks more like what I would expect.

**Comment by hellojere** [comment]
Cheers! I'm in the middle of the installation process at the moment - looking good here, thanks - but will try that one in case there are any issues. 

Might be handy to include this in the repo though, should simplify the process for others.

**Comment by baughmann** [comment]
Yes, but I would like to test it on another system first. I'm getting a second system this weekend, so if no one tries it by then I will try it myself.

Best of luck with the install! Reach out if you have issues.

**Comment by hellojere** [comment]
@baughmann tested and works just as my custom made did.  

The memory seems to be capped to 2400 MHz - any suggestions for that? 
What I have is: HyperX HX436C17PB3K4/64 Predator DDR4 64 GB (Kit 4 x 16 GB), 3600 MHz CL17 DIMM XMP

Also, have you disabled SIP at some point? I need to have it disabled in order to use TotalSpaces.

**Comment by hellojere** [comment]
Also getting faded colours on one of my two displays. Oddly it did work on couple boots, and looks normal whilst its booting, but when the log in screen comes it's very much faded. 

Should have taken some notes from the old BIOS, as there the RAM was reporting correctly, but I shall see tomorrow - time to sleep.

**Comment by hellojere** [comment]
I'll just keep posting here, let me know if to do otherwise. 

Found on TonyMac that there's a beta BIOS F9g available. 
> BIOS F9g unlocks CFG-Lock (MSR 0xE2) by default

For the above reason, this version was heavily recommended. Updated and followed [this guide](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/) for the BIOS config (details under `Spoiler: Firmware F8 and Newer`). The RAM shows up correctly at 3600Mhz now 🥳

The faded colors don't seem to happen with just one display in use, so I'll get back on that shortly. Also yet to figure out how to disable the SIP. Found already how that should be turned off, but didn't do anything for me.

**Comment by hellojere** [comment]
Party time 🥳  🎉

With a combination of the BIOS config and yours, all seems to be working correctly now. Mainly disabled the Wi-Fi from the above, rest is according to that guide. 

SIP required [to override the variable](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip) due to NVRAM.  

The faded display was just some Big Sur issues - there's a new setting in System Preferences for `High Dynamic Range` - oddly this only got enabled when I connected the 2nd display, but unchecking that did the trick. 

Thanks again. Learned a lot and hopefully I can contribute in the long run.

**Comment by baughmann** [comment]
I'm glad to hear it! Thanks for the tip, I'll look into that today. I'm updating my wife's machine mobo to the Designaire and it's the perfect time to try to disable SIP to fix the NVRAM.

I'm glad to hear you're interested in helping, I could certainly use it! Feel free to chime in on any issue you think you might have some input on. There's always new issues opening up when people need help.

Closing this for now, pending adding my BIOS config to the repo assuming it works on this new system today.
