### ISSUE TITLE
bios

### ISSUE THREAD

**Issue by tnwss** [baughmann/designaire-z390-intel-i9-9900k-opencore#26]
![WechatIMG475](https://user-images.githubusercontent.com/22867489/101525282-0d0a0380-39c6-11eb-9864-47918869f766.jpeg)
![WechatIMG477](https://user-images.githubusercontent.com/22867489/101525286-0e3b3080-39c6-11eb-89d0-ae5aa1928841.jpeg)

**Comment by baughmann** [comment]
Hmm, looks like bios configs aren’t swappable between motherboards. That blows. Thanks for the issue, I will take it down.

Are you able to use the BIOS guide to configure it manually?

**Comment by baughmann** [comment]
Closing. BIOS config has been deleted.

**Comment by baughmann** [comment]
@tnwss Try this 
[BIOS_Config.zip](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/files/5673089/BIOS_Config.zip)

**Comment by tnwss** [comment]
I have installed your prompt manually! Thank you very much

**Comment by baughmann** [comment]
@tnwss So, the BIOS config I attached worked?

**Comment by tnwss** [comment]
Wait a moment. I have time to test it for you. The other lightning interface doesn't work

**Comment by baughmann** [comment]
Thank you sir!

Wait, the Thunderbolt 3 port in the back doesn't work?

**Comment by tnwss** [comment]
Yes. Ports don't work, sometimes they work!

**Comment by tnwss** [comment]
I can't speak English, I'm sorry I used the translation software!

**Comment by baughmann** [comment]
No worries! Thats super weird. Does the BIOS config fix that? Also, see #21
