### ISSUE TITLE
Big problem with Big Sur

### ISSUE THREAD

**Issue by tamasharasztosi** [baughmann/designaire-z390-intel-i9-9900k-opencore#28]
**Describe the bug**
Hello! I'm trying to get Big Sur working on my desktop but I'm getting hopeless.
I changed to Opencore from Clover with clean install (since a new Clover failed to boot).
I tried to install right into Big Sur with no luck. Then I succesfully installed Catalina with dualboot, everything worked. So yesterday I tried to update to Big Sur from Catalina and the same problems started. Now I can only boot into MacOS BigSur Installer or Windows. The installer fails at a point (it says "there was a problem while preparing the installer"). I tried to boot from my Catalina pendrive, it said something like "you cant boot from Catalina since you have a newer OS installed".
So I created Big Sur pendrive with your updated EFI (I updated kexts and set "-v" arg). Tried to install it to my main drive.. At around 13 mins left it stops. The log I got from installer says nothing (I will update my post with it).
I setup SMBIOS correctly (found a serial that said Purchase data not validated, when I check it now it says it not valid), 
I repaired my drive in OSRecovery. BIOS setting all the same, I am on the lastest BIOS. Windows 8/10 featues was set to Other but I set it as you did. One other thing I did late night was that I updated Opencore with debug files (BOOTx64.efi, EFI/OC/Bootstrap/Bootstrap.efi, EFI/OC/Drivers/OpenRuntime.efi, EFI/OC/OpenCore.efi) it worked but then it loaded into OS installer screen (so I think no boot or kernel issue)
I am getting really hopeless.
Do you have any thought?
Thank you!

**OpenCore Logs**

Full logs downloadable from here: https://www.dropbox.com/s/wxnbrl2qjzo70g6/Logs.zip?dl=0

> disk0s2 is not convertable to APFS: the volume was not formatted as Mac  Os extended (journaled)
> disk2s1 already has an install user and must be erased.
> Will need to use bundled in license doc
> Error Code = 1004 "error at preparion the installer", code=2 CRC mismatch got:0x82f6337b, expected:0xe3f031b8

![IMG_1737](https://user-images.githubusercontent.com/25348566/101934704-3e5d1c00-3bde-11eb-854b-e0c765fe43eb.jpeg)

**Screenshots**
Problem when I boot from inside "Install MacOS BigSur" (My only boot option besides Windows)
("There was a problem while preparing the installer")
Also in this section in the upper menu there's no option for opening install log.
![1](https://user-images.githubusercontent.com/25348566/101877786-db906400-3b8e-11eb-9ccd-da91d51bc907.jpg)
The only drive I can restart to after installation failed:
![2](https://user-images.githubusercontent.com/25348566/101877891-fc58b980-3b8e-11eb-8c11-959a73da193f.jpg)

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i9 9900 - BIOS: turned on iGPU as you mentioned Sidecar issue
 - GPU: RX580
 - Motherboard: Designaire Z390
 - RAM: Kingston HyperX 32GB
 - SSD: Samsung Evo 970 M.2 NVMe (NVMe - 500GB) - TRIM WAS ENABLED IN CATALINA (could it be a problem?)
 - BT/Wi-Fi: WTXUP Broadcom BCM94360CS2 Bluetooth/Wi-Fi Card (Fenvi T919 with BCM94360CD is on it's way)

**Additional context**
I will update this post with more info.
I really appreciate any help you can provide!

**Things I will try**

I have your SSDT-PMC but what if I set LegacyEnable and LegacyOverwrite true...
![Képkivágás](https://user-images.githubusercontent.com/25348566/101890353-e2c06d80-3ba0-11eb-8e6a-361b8d36a8bf.JPG)
![Képkivágás1](https://user-images.githubusercontent.com/25348566/101890370-e8b64e80-3ba0-11eb-8a96-b067f52855e8.JPG)

AppleDebug will be set to true, Target to 67
![Képkivágás](https://user-images.githubusercontent.com/25348566/101898683-d3dfb800-3bac-11eb-8b8d-647e6dc1a17e.JPG)
![Képkivágás2](https://user-images.githubusercontent.com/25348566/101898885-2a4cf680-3bad-11eb-9fc7-9ce525e6caa8.JPG)

**Comment by baughmann** [comment]
Are you able to install the OS to another hard drive, just to see if it works?

I'm really at a loss here but it seems like macOS might not like something about your drive configuration. I also have a 970 EVO as my primary, but I don't remember if I enabled trim or not, so it's probably whatever the default is.

What I would recommend as your first steps.

Attempt 1:
- Unplug every drive except for your NVMe
- Boot into the Catalina or Big Sur Installer USB
- Go to Disk Utility and Erase your NVMe and re-format it with APFS - GUID
- Try to re-install Catalina on that drive

If that fails, then to see if it's a weird drive config issue:
- Unplug everything except for a 860 EVO (or whatever non-NVMe SSD you have)
- Then retry the same thing we did in "Attempt 1", but with this drive instead
    - Go into the Catalina or Big Sur Installer USB
    - Go to Disk Utility and Erase your NVMe and re-format it with APFS - GUID
    - Try to re-install Catalina on that drive

**Comment by tamasharasztosi** [comment]
Thank you for your answer!

So I almost tried everything. 
1. Formatted the 970 EVO into exFAT, logged into Windows, with Samsung Magician turned off TRIM, ran some diagnostic test, everything passed with no errors.
2. Pluged out Windows's NVMe (also Intel wireless card), reformatted 970 EVO (first to HFS then APF) seemed like it works then now at 12 mins it rebooted and after that started an installation process which failed after some time with the same error I had earlier.
3. I read somewhere that XFX RX580 could cause kernel panic at installation. So I unplugged it. Booted from Big Sur pendrive but I could'nt get until installation UI, it rebooted everytime at white Apple logo after around 30 secs.

The only things I have to change in your config are Serial,MLB,UUID. I generate them with GenSMbios. I also you a Mac to write the Big Sur image on the drive. 
Did you updated your setup to 0.6.4? 
What else could go wrong? 
Thank you !

**Comment by baughmann** [comment]
Wow, that's a lot of stuff. The only thing that's different about your setup is the GPU. It's possible you need a different `slide` value in the boot args. Have you looked up what you need to do for the RX580 with OC?

Also, I have not yet update to OC 0.6.4

**Comment by baughmann** [comment]
Just to be clear, you did try the following, right?

- Unplug *every disk* except the NVMe you want to install macOS on and the USB installer
- Boot into USB installer
- Erase the NVMe and re-format as APFS using Disk Utility on the USB installer
- Try to install to that NVMe

**Comment by tamasharasztosi** [comment]
> Just to be clear, you did try the following, right?
> 
> * Unplug _every disk_ except the NVMe you want to install macOS on and the USB installer
> * Boot into USB installer
> * Erase the NVMe and re-format as APFS using Disk Utility on the USB installer
> * Try to install to that NVMe

Yes, I did in 
`2. Pluged out Windows's NVMe (also Intel wireless card), reformatted 970 EVO (first to HFS then APF) seemed like it works then now at 12 mins it rebooted and after that started an installation process which failed after some time with the same error I had earlier.`

I will try to set stuff for RX580 as it mentioned in this repo: 
[https://github.com/teimor/OpenCore_GA-H97-D3H_RX580](url)

**Comment by baughmann** [comment]
Any lock with the RX580 stuff @tamasharasztosi ?

**Comment by tamasharasztosi** [comment]
Nah, no luck, same error message. Even with this guy's EFI (with updated kexts):
[https://www.tonymacx86.com/threads/guide-macos-big-sur-11-0-1-on-z390-aorus-elite-board.306236/](url)

Seems like the error happens when the installer tried to unzip a file in SharedSupport.dmg.
Efi_updater was the to "No".

**Comment by baughmann** [comment]
Have you tried making new install USBs as well, maybe one with Catalina and one with Big Sur?

**Comment by tamasharasztosi** [comment]
Yes, I reformatted the USB stick almost everytime I load a new EFI on it. Tried with an other pendrive same on luck. With the Kinston HyperX Savage 64GB pendrive I was able to install opencore Catalina.
I checked I succesfully unzipped on mac the 
`/Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg/com_apple_MobileAsset_MacSoftwareUpdate/6c799f422b6d995ccc7f3fb669fe3246fd9f61aa.zip`

what seems to fails during the installation with texts like "Failed to supply bytes" and "Finished extracting: failed"

**Comment by tamasharasztosi** [comment]
The only post I found something similar is this:
[https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-2442](url)
However I don't really understand the way... how does it differs from what I did with install it to an other NVMe drive.
What do you think?

**Comment by baughmann** [comment]
I'm really not sure. How about installing Catalina again, putting my EFI on there and updating to Big Sur through that?

**Comment by tamasharasztosi** [comment]
Will do that!

**Comment by baughmann** [comment]
Make sure to copy the EFI onto the Catalina drive's EFI partition and leave every other drive (including the USB) out when updating to Big Sur. I can't think of a reason that it shouldn't work in that case.

All I know is that I have yet to attempt an install straight to Big Sur myself.

**Comment by tamasharasztosi** [comment]
Ok, Catalina up and running, didnt sign in to iCloud, booted from your latest EFI, no pendrives connected, downloading Big Sur...
Fingers crossed..

**Comment by baughmann** [comment]
Best of luck!

When you say 

> ... booted from your latest EFI ...

I assume you mean you moved it to the macOS SSD's EFI partition?

**Comment by tamasharasztosi** [comment]
Yes I did! Same error!

**Comment by baughmann** [comment]
That doesn't make any damn sense man...

I'm sorry, I really have no idea what to do now

**Comment by baughmann** [comment]
It's a long shot, but maybe try disabled integrated GPU while installing? I don't know...

**Comment by baughmann** [comment]
You could also try [this](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/post-2159761) (CMF + F for "Used my 2020 MacBook Pro to install Big Sur onto an external"), but you wouldn't be able to use your NVMe drive (unless there's an adapter you can buy)

**Comment by tamasharasztosi** [comment]
Checked, actually it was on Disable iGPU, now I tried with Enabled, same error.

Going to try this workaround:

**- Clone the NVMe SSD to a SATA SSD mounted in an external USB 3.0 enclosure.**
**- Connect the SATA SSD to another Hackintosh (or Mac).**
```
Boot the Hack using its own EFI folder.
From the OpenCore Picker, boot the external SATA SSD.
Login to macOS and perform in-place update through System Preferences --> Software Update.
Shutdown the system and remove the SATA SSD.
```
**- Connect the SATA SSD to the original Hackintosh.**
```
Boot the Hack and select the SATA SSD.
Login to macOS.
Make sure everything is okay.
Then clone the SATA SSD to the internal NVMe SSD.
```

**Comment by baughmann** [comment]
Yes, that's a good idea. You have, like, the *exact* same hardware as me except for that GPU, and I have no idea how that would cause this error. You have the 9900k processor right?

**Comment by tamasharasztosi** [comment]
Yes, I do. Also visible in "About this Mac", everything is correct.

**Comment by baughmann** [comment]
Even if you just remove the serial numbers from the `config.plist` it should work

**Comment by tamasharasztosi** [comment]
> Checked, actually it was on Disable iGPU, now I tried with Enabled, same error.
> 
> Going to try this workaround:
> 
> **- Clone the NVMe SSD to a SATA SSD mounted in an external USB 3.0 enclosure.**
> **- Connect the SATA SSD to another Hackintosh (or Mac).**
> 
> ```
> Boot the Hack using its own EFI folder.
> From the OpenCore Picker, boot the external SATA SSD.
> Login to macOS and perform in-place update through System Preferences --> Software Update.
> Shutdown the system and remove the SATA SSD.
> ```
> 
> **- Connect the SATA SSD to the original Hackintosh.**
> 
> ```
> Boot the Hack and select the SATA SSD.
> Login to macOS.
> Make sure everything is okay.
> Then clone the SATA SSD to the internal NVMe SSD.
> ```

So here comes my new misery.
Bought a 240GB SSD, cloned the drive.
The problem is that I have only a MacBook Air Mid 2012 what is not supported by Big Sur.
I should use an other EFI I guess since with your EFI the Apple logo oversized and the OS doesn't load in.

**Comment by baughmann** [comment]
Yeah maybe you'll have better luck with another EFI? I'm really just not sure how it does not work since we have nearly identical hardware.

**Comment by baughmann** [comment]
Closing for now, but feel free to re-open if I can help

**Comment by tamasharasztosi** [comment]
> > Checked, actually it was on Disable iGPU, now I tried with Enabled, same error.
> > Going to try this workaround:
> > **- Clone the NVMe SSD to a SATA SSD mounted in an external USB 3.0 enclosure.**
> > **- Connect the SATA SSD to another Hackintosh (or Mac).**
> > ```
> > Boot the Hack using its own EFI folder.
> > From the OpenCore Picker, boot the external SATA SSD.
> > Login to macOS and perform in-place update through System Preferences --> Software Update.
> > Shutdown the system and remove the SATA SSD.
> > ```
> > 
> > 
> > **- Connect the SATA SSD to the original Hackintosh.**
> > ```
> > Boot the Hack and select the SATA SSD.
> > Login to macOS.
> > Make sure everything is okay.
> > Then clone the SATA SSD to the internal NVMe SSD.
> > ```
> 
> So here comes my new misery.
> Bought a 240GB SSD, cloned the drive.
> The problem is that I have only a MacBook Air Mid 2012 what is not supported by Big Sur.
> I should use an other EFI I guess since with your EFI the Apple logo oversized and the OS doesn't load in.

So this method worked, however with 11.1 I had to update to 0.6.4.
Thank you for all your help!
Closed!

**Comment by baughmann** [comment]
What, really?? That was all it took? Nuts! I just posted a 0.6.4 EFI the other day, but I didn't make it a release. If you clone the repo the EFI folder should be good to go.

**Comment by tamasharasztosi** [comment]
Yes it works nice with some flows at at moment. 
1. Seems like when it would go to sleep it just reboots.
2. Geekbench5 score dropped from Catalina's 9100 to 8200
3. DRM works, Netflix in Safari doesnt

I created a EFI with OCgenX with your EFI it doesnt boot. Also I put in USBWakeFixup.kext. Maybe thats the one causing the sleep issue.

**Comment by tamasharasztosi** [comment]
So only for debugging reasons I post here my log when I try to boot with your EFI.
![IMG_1762](https://user-images.githubusercontent.com/25348566/102715919-a0054080-42d8-11eb-8a8a-4e0152d11bfd.jpg)

I'm using his EFI with moderate success (it reboots instead of sleep).
[https://github.com/joostiphone/Z390-Hackintosh-Joost](url)

Thank you for your help!
