### ISSUE TITLE
Kext needed for i211 ethernet and TB3 not displaying in System Properties

### ISSUE THREAD

**Issue by surfing-IT** [baughmann/designaire-z390-intel-i9-9900k-opencore#29]
**Describe the bug**
Hello, I first want to say thank you for all this work that made Big Sur an easy process. 
1. I did need to install the SmallTreeIntel82576.kext (i211) and the IntelMausi.kext (i219v7) to make both ethernet ports work, so please double check and update your documentation if confirmed.
2. The thunderbolt ports aren't recognized in System Information, and IDK how to fix <~ please help

**Expected behavior**
Two working Thunderbolt ports, the built-in ones

**Screenshots**
![Menubar_and_iMac_and_Security___Privacy_and_About_This_Mac](https://user-images.githubusercontent.com/75861510/101953617-7e58da80-3baf-11eb-8cbb-756df6e85d67.jpg)

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i7 9700k
 - GPU: AMD RX 580
 - Motherboard: Gigabyte Designaire Z390
 - Storage: Samsung 1TB Evo Plus NVME - APFS
 - Wifi/BT: Fenvi T919

**Additional context**
Everything else works a treat!
BIOS is identical to the guide, before you ask. =) except that VT-d is enabled for Parallels

**Comment by surfing-IT** [comment]
BIOS is identical to the guide, before you ask. =)

**Comment by ryanpsims73** [comment]
Regarding Thunderbolt, do you mean when you go into system report you don't see them? I have the same issue, but am able to use thunderbolt to drive a monitor and use usb devices on that.

There's a part of the guide over at https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/ that discusses flashing the rom to get better support. I'm not sure how much that differs in practice.

**Comment by baughmann** [comment]
I will re-confirm the need for *both* kexts today and update the EFI accordingly, unless @ryanpsims73 or @hellojere can confirm they've noticed this behavior?

As for TB3, I can confirm @ryanpsims73 situation is mine as well. TB3 does not display in system report, but my TB3 is hot-swappable nonetheless. I cannot confirm however that the TB3 port is operating as a TB3 port and not just a USB 3.1 with a USB-C connector. Maybe @ryanpsims73 knows?

**Comment by baughmann** [comment]
@surfing-IT Let me know if you're having legit problems with the TB3 (not just it showing up in system properties). If you are, feel free to re-open this ticket.

Closing for now as primary issue (Ethernet) is resolved as of commit [574b1c9](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/commit/02d4652debc5c139b9351a1dd2bec1b317f92ede)
