### ISSUE TITLE
Bluetooth keyboard and mouse not working 

### ISSUE THREAD

**Issue by jiribanas** [baughmann/designaire-z390-intel-i9-9900k-opencore#3]
Howdy, I have the exact same hardware configuration as you and the latest BIOS. My Fenvi T919 is in the second PCIe slot (the one further down away from the CPU) because Radeon VII takes a lot of space and the first PCIe slot is blocked but the big GPU. When I use your EFI with the Config.plist modifications as required the system boots to 10.15.6 and Bluetooth is seemingly working but no Bluetooth devices connect. My Apple Bluetooth keyboard and Magic Mouse don’t connect. Nor any other BT devices like AirPods. Since we have the same hardware, I’m guessing your USB mapping should work for mine too out of box. Do you have any ideas or have you had issues with Bluetooth? What PCIe slot is your Fenvi card in?

PS I previously used a Clover EFI and Bluetooth worked as expected.

**Comment by baughmann** [comment]
Hmm weird. I've got all the Apple goodies (AirPods, MM, MK) as well...

Are you in this slot? IIRC (it was a *long* time ago), the USB mapping requires the exact same PCI/e slot.

![bt_card](https://user-images.githubusercontent.com/6177411/89357383-56e88300-d68e-11ea-8a69-a509c90d2314.png)

**Comment by jiribanas** [comment]
Yes, the same slot. The Fenvi card requires a USB connection. The MB has only a single USB slot down there (see the red circle on my photo) so I used an extender (also shown on my photo) to get two USB connections from that single MB slot. One goes to Fenvi and the other one is for my CPU cooler. I can't disconnect the CPU cooler to test this theory but do you think that might be the issue? Again, the BT is working fine with the Clover EFI, just not the OC one. 

![IMG_4465](https://user-images.githubusercontent.com/14013683/89357823-9bc0e980-d68f-11ea-91cf-49ac073b7f25.jpg)

**Comment by baughmann** [comment]
I actually had to do the same thing you did for my cooler, haha. Got the same double-sided foam too.

If you didn't have the same setup working in clover, I'd say you should look into the card or the 1-to-2 USB adapter. However, that's kinda out the window.

Just to dot our "I"'s and cross our "T"'s:
- I would say let your machine cool down for a bit, unplug your cooler and plug the card directly into the motherboard. A few minutes without active cooling for testing won't kill it (I should know, I did this same testing when making the `USBPorts.kext`. At worst it'll shut down before it damages itself, just don't make a habit of it).
- Also try turning off then on your Magic* stuff before trying to pair. When I switch machines I have to do this.
- Meanwhile, I will do some digging to see how I made the `USBPorts.kext`. You may end up having to make your own. You will definitely need to verify the ports are the same.
- Which hardware revision is yours? Mine is `1001`. If yours is different, we may want to look into the changes to see if they changed the port addressing for some stupid reason.

**Comment by baughmann** [comment]
We can also compare this screenshot from Hackintool with what you see on the same tab
<img width="1572" alt="Screen Shot 2020-08-04 at 8 54 01 PM" src="https://user-images.githubusercontent.com/6177411/89359814-acc02980-d694-11ea-8e9b-13bddc3db8a4.png">

**Comment by jiribanas** [comment]
My MB says revision 1.0 on the box. I'll check in BIOS yet. Hackintool looks like this for me:

<img width="1047" alt="Screen Shot 2020-08-05 at 2 02 25 PM" src="https://user-images.githubusercontent.com/14013683/89447791-98c40880-d724-11ea-8741-46fc266c9c71.png">

I am not familiar with Hackintool or how to make my own USBPorts.kext. I'll do some reading. If I copy the USBPorts.kext from my working Clover EFI to a copy of your EFI, the OpenCore EFI doesn't give me any USB at all.

**Comment by baughmann** [comment]
Hmm that's weird. I was using my `USBPorts.kext` with Clover before switching to OC and didn't change anything at all.

Are you using my entire EFI folder, including `USBInjectAll.kext`?

**Comment by baughmann** [comment]
Our ports are pretty different. How about we both unplug everything we can (including KB, just leave the mouse) and take another screenshot? I know I have a TB3 hub plugged in, and it looks like you might as well.

**Comment by baughmann** [comment]
I re-arranged your USB device order to match my own. Once you unplug everything, restart your computer, and post a screenshot, we will see what has changed.

<img width="1675" alt="bt_probs" src="https://user-images.githubusercontent.com/6177411/89469487-84453780-d747-11ea-9f33-a08cfde9f587.png">

**Comment by baughmann** [comment]
Doing some more [digging around](https://www.insanelymac.com/forum/topic/339900-insanely-hackbeast-ga-z390-designare-thunderbolt-full-dsdt-patches-clover-opencore/?page=2&tab=comments#comment-2688150), it looks like `HS14` might be the culprit after all.

My memory on this subject is coming back a little bit. You'll notice that there is [no entry for `HS14` in my `USBPorts.kext`](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L144).

Can you please re-verify that you have my `USBPorts.kext` in your EFI folder my opening it up (right click > view package contents) and making sure that there is no entry for `HS14`?

**Comment by baughmann** [comment]
@jiribanas I'm assuming you figured this out because you never responded. Closing for now, feel free to re-open if it's still broken.
