### ISSUE TITLE
Can't seem to [REPLACEME] 

### ISSUE THREAD

**Issue by jahwookie** [baughmann/designaire-z390-intel-i9-9900k-opencore#30]
This is the i9-9000 system we've discussed recently. Everything running smooth as butter under Big Sur, except I keep failing on one fine tuning point: tried several times using the SMBIOS utility to generate new serial, UUID numbers, but they don't stick. Maybe this previously handy tool is outdated. Any other methods to try, or suggestions on something I might be missing? Thanks.

**Comment by baughmann** [comment]
You mean when you restart and then go into the `config.plist` the changes aren't there anymore?

**Comment by jahwookie** [comment]
Good question! Actually, they ARE still in the config.plist, but don't show
up when I open "About This Mac" from the apple on the top bar. Thinking now
I should disconnect the other drives to make sure which one I'm booting
from.

**Comment by baughmann** [comment]
As in the SN field is blank in "About this Mac"?

**Comment by jahwookie** [comment]
Well, blank unless you count [REPLACEME].

**Comment by baughmann** [comment]
Lol. Maybe try clearing your NVRAM? I'm not sure that it would make much of a difference though...

**Comment by jahwookie** [comment]
I'll try that and some other things, and report back later. Thanks, as
always, Nick.

**Comment by jahwookie** [comment]
Okay, all clear and good to go. I'm realizing that using Carbon Copy Cloner
on internal drives can create cases of mistaken identity, even as to which
drive is booting the system. Now I've got it narrowed down to the 970 Pro
NvME drive, which is a lot faster than the identical drive I've
disconnected for now. I think backing up to externals is the way to go for
me going forward! Thanks, JW


[image: Screen Shot 2020-12-16 at 2.34.49 PM.png]

**Comment by hellojere** [comment]
@jahwookie Seems like something changed to worse with internal drives and Carbon Copy Cloner lately. For me it's forcing an identical name as the original drive no matter what, making booting quite a lottery. 

Seems like externals are the way to go for the time being indeed.

**Comment by baughmann** [comment]
@jahwookie We good to close this issue?

**Comment by jahwookie** [comment]
Yes, Nick! I simply made the mistake of having two identical, bootable
drives in the same system (CC Cloner even duplicates the name). So, I was
mistaken as to which one was booting until I disconnected the other. One
thing I did want to add, as more a report and a question: after
successfully doing the 11.1 upgrade from Apple, my graphics started going
black for a few seconds, periodically at first, then so often the machine
was not usable. So, I plugged in your 12.15 updated EFI, which entirely
cleared up the issue. Thank you very much for that!

I did notice this time, when clearing out the EFI section in the bootable
drive, an extra folder called "Apple" that I'm pretty sure was not part of
your older package, and which I don't think I've seen before. It appeared
to be firmware of some sort, and I wasn't sure which way to go, but went
ahead and trashed it with the rest. From the result, that seems to have
been the right thing to do. Yes?

Best, and definitely can close the issue as requested.

**Comment by baughmann** [comment]
@jahwookie Sweet, glad I could help!

Yeah, I haven't done much investigation of the Apple folder that occasionally gets created on EFI partitions. My mindset is, if the OS generated it once, it can easily re-generate it again if it needs to. I tend to delete them whenever making EFI changes.

Best of luck with your new OS, and take care.
