### ISSUE TITLE
Problems Updating BIOS

### ISSUE THREAD

**Issue by achillespilot** [baughmann/designaire-z390-intel-i9-9900k-opencore#31]
Hi Nick, 

This isn't strictly related to Hackintosh configuration etc so feel free to delete if not appropriate. However, any help appreciated!

I thought now was the time to update to Big Sur but first I need to update my BIOS as I'm still on F6. I cannot for the life of me get the BIOS to update. I need to use Q-Flash as I don't have a Windows drive installed to use the Windows utility for updating. It always successfully verifies the file but then when the actual BIOS flash begins it sticks at 0%. I am able to successfully reboot and the F6 BIOS seems untouched. 

I've tried:

- different USB drives all formatted FAT32 (although they've been 16GB ones - could that be an issue? Need to be smaller?)
- different versions of the BIOS (specifically F7 and the latest F9i I think) so its not file specific
- different USB ports (used the front one at first but then switched to one of the rear ones)

Is there anything I'm missing? It's almost like the current BIOS is set to Read Only and cannot be written over... is there a setting buried somewhere that could be doing that? Do I even need to update it or will Big Sur run fine on F6?

Thanks again,
Gavin

**Comment by achillespilot** [comment]
Disregard - CMOS reset seems to have enabled it.

**Comment by baughmann** [comment]
I was gonna saw I know that there are ways to lock it, but glad to see you figured it out!

Best of luck with the upgrade, let me know if something goes wrong.

Closing for now
