### ISSUE TITLE
Automatic macOS update stuck on 11.0.1

### ISSUE THREAD

**Issue by hellojere** [baughmann/designaire-z390-intel-i9-9900k-opencore#34]
Had this issue prior the latest EFI already, but just updated the EFI to the latest version and it's still present. 

Basically Software Update states "Your Mac is up to date - macOS Big Sur 11.0.1" despite the `11.1` being out already. 

I tried searching what could be causing this without any luck. Any tips appreciated.

**Comment by baughmann** [comment]
@hellojere 

I’ve heard of people having that issue with OpenCore but I have yet to experience it myself. Both I and my wife have both updated via Apple updater. Let me look into it a bit.

**Comment by baughmann** [comment]
What does [this](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#broken-seal) do for you?

**Comment by baughmann** [comment]
Please note, as per those docs, you'll need OC 0.6.4, so rather than pull from the "releases" page here, you'll need to clone the repo. I never made a release for OC 0.6.4, just updated the repository (which is basically the same thing)

**Comment by hellojere** [comment]
@baughmann Thanks, that could be it. I ended up updating by downloading the whole installer from AppStore, but will try this out soon. As for this repo, I'm pulling the changes with git, so all good there - handy to see the diffs to for any customisation on my end.

**Comment by baughmann** [comment]
Sweet. Well, I’ll close this for now then. But, the next time and update come out, feel free to re-open it if that link I gave you doesn’t help.
