### ISSUE TITLE
Can't Boot OpenCore

### ISSUE THREAD

**Issue by jaywehner** [baughmann/designaire-z390-intel-i9-9900k-opencore#37]
I have the identical hardware as you. The only thing different is the video card. I can't get the USB to boot. All I see is the option for windows to boot. I select boot from USB then it just goes to a screen where all I can select is windows to boot. Opencore never gives me the option to boot the USB. Not sure if this is specific to our hardware or an issue with Opencore. I have reset and changed the BIOS settings according to the OpenCore tutorial and according to yours and nothing. Any help is appreciated.

**Comment by baughmann** [comment]
Have you placed the EFI folder onto the EFI partition of the USB?

Maldonado, which BIOS version are you running?

**Comment by jaywehner** [comment]
I'm using the FAT32 method where the root of the USB contains two folders:
com.apple.recovery.boot
EFI
I'm using the latest BIOS from Gigabyte version F9i

**Comment by baughmann** [comment]
I’m not familiar with that method. However it sounds like that could be the cause.

I suggest following the method recommended by the documentation

**Comment by jaywehner** [comment]
You can close the issue. I found it to be the USB type. I found a 32GB Trinity USB 3.0  in a junk drawer and everything installed correctly. I know people have issues with using 3.0 so that might have been the issue.

**Comment by baughmann** [comment]
Hmm that’s interesting. Well, glad you found success.
