### ISSUE TITLE
Top 2 USB ports missing?

### ISSUE THREAD

**Issue by jordanurbs** [baughmann/designaire-z390-intel-i9-9900k-opencore#39]
Hey there, I use the exact same hardware--thanks for sharing, it's helped me move over from Clover. My only issue is that the motherboard's top 2 USB ports (next to the old school port for a mouse) don't read anything (they worked fine before)

At first I was trying to piece together different components from your repo and do most of it myself (I use the Fenvi card for Wifi, for example, but a USB dongle for bluetooth)--but I ended up just duplicating your repo directly with the only modification being iMacPro1,1 instead of iMac19,1 (which I have heard is better for pro apps). 

Now those top 2 USB ports don't work which feels strange, and the BT dongle only can handle a single device connection but works fine for airdrop. I may have slightly different BIOS settings but I scanned through yours and didn't notice anything in particular.

Any ideas why those 2 ports aren't in operation?

**Comment by baughmann** [comment]
Hmm yes I've never had good luck with a USB BT dongle on a Hackintosh. Why aren't you using the Fenvi for your BT as well?

I cannot say I've been able to reproduce this, as the top ports are functional for me. Do they work for you in Windows and just not in Mac?

Can you make a backup of your BIOS config, and load mine and see if it changes anything?

**Comment by jordanurbs** [comment]
Hey thanks for the response! I am closing the issue because I ended up just re-inserting the Fenvi (it had given me problems with my first build for some reason), directly applying your BIOS, and using your build exactly as is. And now everything is perfect--Ha! Cheers!

**Comment by baughmann** [comment]
Good to hear, enjoy!
