### ISSUE TITLE
Random freeze on Catalina

### ISSUE THREAD

**Issue by LeCarlo23** [baughmann/designaire-z390-intel-i9-9900k-opencore#41]
Maybe the issue comes from the GPU? Radeon VII?
Any tweak to fix it?

**Comment by baughmann** [comment]
I'm not sure. Do you have any logs? Can you elaborate on the behavior?

**Comment by LeCarlo23** [comment]
I try to update my os from Catalina to Big Sure with your EFI, but after restart, I got this message and my computer do not boot any more.

![IMG_0529](https://user-images.githubusercontent.com/72163476/110641232-0c922c00-81b2-11eb-81c0-7f724233649d.JPG)

There is a solution ?

**Comment by baughmann** [comment]
Please verify that:
- You are using my BIOS
- You used my EFI folder only and no custom kexts/drivers
- You did not alter the `config.plist` file

Please also tell me which version of Big Sur you are trying to install.

**Comment by baughmann** [comment]
I'm currently not using that version of Big Sur (I'm still on 11.2) and I'm also not using that BIOS version. I'm using the BIOS version described in the readme.

This evening if I can I will try to update OpenCore and my BIOS firmware and see if I can get it working.

Until then, I would recommend you update OpenCore and make the necessary changes to your `config.plist` as that will likely resolve your issues.

**Comment by baughmann** [comment]
Well, you should have your EFI on a USB, right? You need to make these changes on your other Mac, or any system that can mount the EFI partition of a USB stick.

**Comment by LeCarlo23** [comment]
Yes, and then I'll reinstall the OS? Right?

**Comment by baughmann** [comment]
No, if you fix the EFI folder and put it on a USB, then you just boot from the USB and select your existing installation in the boot picker. You don't need to reinstall unless something went wrong during installation.

**Comment by LeCarlo23** [comment]
Solved, thank you

**Comment by baughmann** [comment]
Sweet, closing.
