### ISSUE TITLE
USB3.0 not working for a particular device

### ISSUE THREAD

**Issue by chetrf** [baughmann/designaire-z390-intel-i9-9900k-opencore#42]
First let me say thanks soooo much for putting this out there.  I am on MacOs Catalina (using the release specific for Catalina) and everything works except for my Salaea logic analyzer.  It is a USB3.0 device that needs a fair amount of bandwidth.  I noticed a mention about not needing a USB map for Big Sur.  Have you had better luck with USB devices since moving to Big Sur?  BTW I do have pretty much the exact same hardware config as this repo was tested on.  I am wondering if I should try this out on Big Sur?

**Comment by baughmann** [comment]
In general, I've definitely had better luck with IO in Big Sur. However, I do not use any specialty USB devices.

If you're feeling lucky, you can update your BIOS to the latest, clone my EFI and update OpenCore and then use it to install Big Sur.

However, this EFI is currently not up-to-date with the latest version of Big Sur. I've been super busy and I have not even had a few minutes to take care of this yet. I'll try to do it again today after work, so maybe check back later and see if I've done it.

If I've not done it, feel free to pester me about it. Maybe it'll light a fire under my ass enough to get it done finally.

**Comment by jahwookie** [comment]
Hi, Nick -

FWIW it's worth, I've done the upgrades direct from Cupertino at
least twice now, starting from your most recent EFI. Fingers crossed, and
every case is different, but all good in my machine so far!

**Comment by baughmann** [comment]
@jahwookie Coming to save the day as always! Can you make a PR and I can test it out? Maybe on a separate branch?

**Comment by jahwookie** [comment]
That sounds way above my abilities, sorry. Hanging on by my fingernails
here.

**Comment by baughmann** [comment]
@jahwookie No worries man. Just to clarify, did you update MacOS and *not* update OpenCore, or did you update both? Just out of curiosity.

**Comment by jahwookie** [comment]
Yes, just the Mac OS. No tinkering with your fine work until and unless you
say so!

**Comment by chetrf** [comment]
Do you have any plans to update Big Sur any time soon.  I would like to try Big Sur, but I am assuming if I download it now, it will be out of sync with what you currently have in a stable state?  Thanks.

**Comment by baughmann** [comment]
@chetrf Yeah. I know I've been delaying it for *way* too long. I'm busy and lazy. However, Ive just updated OC and all kexts and drivers. I'm updating Big Sur as we speak and will let you know if/when it succeeds.

**Comment by baughmann** [comment]
@chetrf @jahwookie Looks like the latest EFI release is 👍 for Big Sur 11.2.3

**Comment by baughmann** [comment]
Closing for now to due lack of activity. Re-open if necessary.
