### ISSUE TITLE
DRM not working

### ISSUE THREAD

**Issue by Z390-designhac** [baughmann/designaire-z390-intel-i9-9900k-opencore#43]
When I try to play my movies on Vudu and Amazon Prime Video, it's not running in HD.  
Using Chrome 89.0.4389.114
I disabled the iGPU but nothing changed. Also tried changing to SMBIOS to iMacPro1,1. 
Big Sur 11.0.1 (20B29)
![Untitled](https://user-images.githubusercontent.com/75035056/113760508-ed68ba80-96db-11eb-9600-2a77ed33c1f8.jpg) 
![Screen Shot 2021-04-06 at 1 23 26 PM](https://user-images.githubusercontent.com/75035056/113760555-f9547c80-96db-11eb-8582-262d15b5e706.png)
![Screen Shot 2021-04-06 at 1 22 59 PM](https://user-images.githubusercontent.com/75035056/113761410-0a51bd80-96dd-11eb-87bb-5c5926611cb5.png)

**Hardware Specifications
 - CPU: [Intel Core i7 9700k]
 - GPU: [MSI NVIDIA GeForce GT 710 2 GB]
 - Motherboard: [Designaire Z390]
 - Storage: [Samsung 970 Evo 1 TB APFS]

**Comment by baughmann** [comment]
@Z390-designhac Sorry for not getting back to you sooner. I was able to replicate this issue on my system.

I can see the docs state "[Safari 14 and macOS 11, Big Sur are currently unsupported by WhateverGreen's DRM patches](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#fixing-drm-support-and-igpu-performance)", however, it also says "Browsers not using hardware based DRM(ie. Chrome), will have working DRM without any work both on iGPUs and dGPUs," which does not *seem* to be the case here. I was using Chrome and saw the same dialog in Amazon Prime Video that you sw, and just a blank screen in Safari.

To be clear, we don't *know* that this is an issue with our systems per se, as it cables and monitors do have an impact on DRM. That said, idk about you, but I don't have the cheapest cables and I would assume that this is a non-issue.

Time to troubleshoot...

**Comment by baughmann** [comment]
At first glance, looking like we might be SOL: "[WhateverGreen Shiki functionality is not planned for inclusion for macOS 11](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md#drm-compatibility-on-macos-11)"

**Comment by baughmann** [comment]
Closing this issue for now. Waiting on the OC community (esp. Lilu and WG) to fix this, if they do. It's likely that it's pretty low on their list. Feel free to re-open if necessary.

**Comment by Z390-designhac** [comment]
I have an LG 32qk500 I switched the cables, still nothing. I switched to Catalina on a separate SSD nothing.
I made a post on Reddit and the guy said that you need Hardware DRM, not software DRM. but I don't think that's it.
I used to use Clover, and the same thing happened to me. 
But what's interesting is on Clover Vudu said play HD content you need HDCP. But on OpenCore it plays regularly, but it's running at a lower resolution. The one thing I might test out is High Sierra to see if it makes a difference? Thank you for your feedback I appreciate it.

**Comment by baughmann** [comment]
Weird that it doesn’t work on Catalina. Maybe because of your dGPU? Do you have a compatible AMD GPU that you can try?

**Comment by Z390-designhac** [comment]
I had an Vega 64 but I sold it. I was using clover on Catalina it wasn't working. Wasn't able to test High Sierra on my system.

**Comment by baughmann** [comment]
How are you able to use a Nvidia card with 3D hardware acceleration, etc. at the moment?

**Comment by Z390-designhac** [comment]
The Kepler Nvidia Architecture does work with Big Sur.
3D and acceleration works.

**Comment by baughmann** [comment]
Apologies, not too familiar with Nvidia cards these days, unfortunately. 

I really don't know where to go from here, I'm sorry to say. I've got absolutely 0 experience with writing driver software or any other OS-or-below-level software, so I'd say we're stuck waiting on the community, if they ever get around to it.

Are you using your hackintosh as a media box or something? Would it be inconvenient to consider a linux box for this purpose, or is there a specific reason you want to use macOS for this machine?

**Comment by Z390-designhac** [comment]
It's fine I will wait. I like MacOS for applications. But thanks

**Comment by baughmann** [comment]
Sorry man :/ I primarily use it because the development experience is so nice. I have no idea if/when DRM will be fixed.

**Comment by idioma** [comment]
I have full hardware acceleration and working DRM in Safari. The solution: system definition set to iMacPro1,1.

My build:
Z390 Designare with F9j BIOS update
i9-9900k
128GB DDR4 3600
Dual Radeon VII GPUs (32GB Total VRAM)
Samsung SSD 970 EVO 1TB
Genuine Apple Wifi/BT on Broadcom BCM4360  802.11ac on PCI-E Adapter

My OC:
Ver. 0.7.0

MacOS:
Big Sur 11.4 (20F71)

What works:
Audio I/O
GPU accelerated graphics
Thunderbolt
USB 3.1
iMessage
Facetime
NVRAM read/write (startup drive selection, etc.)
HandOff
AirDrop
AirPlay
AdobeCC
H.264 and H.265 hardware acceleration
MetalAPI
Xcode
Apple Chime during boot (Set to Optical Digital Output, but can also work with other audio channels; e.g., headphones, analog speaker, etc.)

What doesn't:
Most thermal sensors (CPU, GPU, Chipset, are not available, even in 3rd-party apps such as iStat)
Sleep (system wakes up immediately from sleep state)

I've attached a copy of my EFI folder, but omitted the Hardware UUID, Serial Number (system), ROM (derived from MAC address), and MLB Serial Number. You will need to generate your own, but this is a pretty straightforward process and well documented here: [https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html)



[EFI.zip](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/files/6728907/EFI.zip)
