### ISSUE TITLE
Keyboard go crazy in open canopy

### ISSUE THREAD

**Issue by eqcq** [baughmann/designaire-z390-intel-i9-9900k-opencore#44]
Thank you so much for this ! I have only one curious problem. I have 4 hard drive and when I'm on the boot screen the arrow of my keyboard are incredibly sensitive. If I push arrow it go immediately to the last choice. And I can't choose my macos install to boot.
I've tried with 3 different keyboard, same issue and the mouse doesn't work.

Have you any idea ?

**Hardware Specifications (please complete the following information):**
 - CPU: [Intel Core i9 9900k]
 - GPU: WX9100 pro
 - Motherboard: [Designaire Z390]

**Comment by baughmann** [comment]
Wowza, that is super weird. I cannot say that I've had this issue, no. Have you had this problem with older versions of OC?

**Comment by eqcq** [comment]
Ok I've fixed it 
in config file I added AppleInput between APFS and AUDIO with some parameters :

![Capture d’écran, le 2021-04-27 à 08 29 48](https://user-images.githubusercontent.com/3581638/116241308-c0378700-a732-11eb-9405-1610aa5dd88a.png)
