### ISSUE TITLE
Is it safe to upgrade to macOS Big Sur 11.3?

### ISSUE THREAD

**Issue by jmtscaff** [baughmann/designaire-z390-intel-i9-9900k-opencore#46]
Is it safe to upgrade to macOS Big Sur 11.3? any thing we need to do before upgrading?

**Comment by baughmann** [comment]
If you do not wish for me to update the EFI, then all you need to do is download the latest versions of all of the kexts and drivers and place them in your EFI folder. You will also need to read the OpenCorePkg change notes to see what you need to change in your `config.plist`. If you miss something in your config, don't worry, OC will tell you what you did wrong on boot. I would recommend that you keep your old EFI on a USB just in case you mess up and need to boot from it again.

**Comment by jmtscaff** [comment]
If you can update the EFI that would be awesome!!!!! 👍

**Comment by baughmann** [comment]
@jmtscaff Just noticed that I'm already using the latest version of OC et. al. As such, probably OK to update. I'm updating right now, so 🤞

**Comment by jahwookie** [comment]
The last two were trouble free for me, so I'll take the plunge tomorrow as
well.

**Comment by baughmann** [comment]
@jahwookie If you don't hear back from me today, then don't do it haha. It means I had to wipe and reinstall.

**Comment by jahwookie** [comment]
10-4 and good luck, sir!

**Comment by baughmann** [comment]
@jahwookie @jmtscaff Looks like we're good to go. Closing this issue.

<img width="780" alt="Screen Shot 2021-04-29 at 8 24 35 PM" src="https://user-images.githubusercontent.com/6177411/116633990-ec1c5d80-a928-11eb-91ef-313a330c65b6.png">

**Comment by jahwookie** [comment]
For me, 11.3 update went fast and seemed smooth, but somehow lost connectivity on most USB ports, including the ones direct into motherboard where I had mouse and keyboard plugged. I plugged them into the two USB ports on top of the (Fractal Designs) case that I had known to be working previously, and everything up and running for now, but maybe I need to tackle that USB mapping thing I'd avoided up to now as confusing and way too system-dependent? One forum repeated several times that all you need to do is disable XHCI Port Limit. Does that seem logical and worth a try? Thanks!

**Comment by baughmann** [comment]
@jahwookie Ruh roh, idk if I checked USB functionality after updating as I use BT for sound and IO.

I would find it weird that the update somehow broke `USBPorts.kext`, but I supposed anything is possible in the world of hackintosh.

Just DL and use `USBInjectAll.kext` to see if that fixes your port issue. It disables the port limit that you've described. Try disabling `USBPorts.kext` when you do it, too.

**Comment by baughmann** [comment]
@jahwookie [Zoinks, scoob](https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/page-3#post-2245176). Looks like the USB ports might need re-mapping.

**Comment by jmtscaff** [comment]
I don't use USB mapping I use USBInjectAll.kext with the following boot arg: `uia_exclude=HS14`
```
                                <key>boot-args</key>
-                               <string>keepsyms=1 slide=0 alcid=7</string>
+                               <string>keepsyms=1 slide=0 alcid=7 uia_exclude=HS14</string>
```
This will exclude that USB HS14 which is the internal Bluetooth / wifi card.
I also updated USBInjectAll.kext to the latest which was the only kexts which needed update.
I will tried the upgrade to 11.3 later today and report back.

**Comment by jmtscaff** [comment]
I did the upgrade and same the USB ports are not working

**Comment by jmtscaff** [comment]
Setting XhciPortLimit to false fixed the issue at least for me using USBInjectAll.kext so in summary I've did
1. Update USBInjectAll.kext to latest
2. Set XhciPortLimit to false
3. Add uia_exclude=HS14 to bot-args to exclude internal Bluetooth card
Now all ports are working

**Comment by jahwookie** [comment]
So far I've done #2 on you list, which restored my ports. Will look into
the other steps this afternoon. Thank you!

**Comment by baughmann** [comment]
@jahwookie @jahwookie

🔥🔥🔥HOT🔥🔥🔥

Latest release will fix USB issues on >= 11.3. If you need it asap you can download the repo's EFI folder and use that. Otherwise I will put out a release after updating to 11.3.1 this evening

**Comment by jahwookie** [comment]
I'll look for that's next release. Everything working okay for now. And
thanks much!

**Comment by baughmann** [comment]
@jahwookie [Release ZIP]( https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/releases/tag/1.2-oc_0.6.8) has been uploaded

**Comment by jmtscaff** [comment]
By the way I installed 11.3.1 and everything went smooth
![Screen Shot 2021-05-07 at 11 09 56 PM](https://user-images.githubusercontent.com/26261627/117526230-59fc0100-af89-11eb-9597-834be225577c.png)
