### ISSUE TITLE
Fixing DRM issue ,playing Netflix/prime on safari

### ISSUE THREAD

**Issue by dkmahakur** [baughmann/designaire-z390-intel-i9-9900k-opencore#49]
Hi ,
I have been trying to get this working since quite a bit of time ,but no matter whatever i try safari always gives 7706 error for Netflix and prime video doesn't play.
Rest everything works for me flawlessly.

What might be the issue,
Z390 designare 
I9 9900k
Radeon rx6900 xt
Bigsur 11.4
O.C 0.6.9
Smbios 19,1

**Comment by dkmahakur** [comment]
Ah sorry for the question just saw your response on the closed issue section.

**Comment by baughmann** [comment]
@dkmahakur no worries! Hopefully it gets resolved

**Comment by baughmann** [comment]
For my own future reference, the issue in question is #40
