### ISSUE TITLE
NOT AN ISSUE - BUT THANK YOU!

### ISSUE THREAD

**Issue by kennyklee** [baughmann/designaire-z390-intel-i9-9900k-opencore#50]
Just wanted to say, that I am SO SO LUCKY that I found this. THANK YOU! Though I am technical, I don't want to spend a lot of my time understanding what all of this means...maybe just barely. Luckily, I have the exact same hardware as you, so this was almost plug-and-play.

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i9 9900k
 - GPU: AMD Radeon VII 16GB
 - Motherboard: Designaire Z390
 - Memory: HyperX Predator Black 64GB

Here is the build: https://docs.google.com/spreadsheets/d/1w_T5e8yBaFpy5BQqGd2LhvbYqS9dXHDutEftbzgSL14/edit#gid=0

The differences are:
* I upgraded to BIOS F9i. Everything worked with your profile, except I had to manuallyenable:
    * Internal Graphics: Enabled (Needed for Sidecar (thanks @QueercoreTrash, #19)). I found this after testing sidecar and seeing that it didn't work.
* I YOLOed and upgraded to BigSur 11.5 (from 11.4), and everything works great!

The VERY MINOR wish I have is that in the beginning part of the bootload, the resolution wasn't low/big icon. I'm sure there are ways to fix this, but the Resolution: Max in OpenCore.  Maybe setting a specific resolution. I'm not too bothered by it.

Once again, thank you!!!!

**Comment by kennyklee** [comment]
I realized I should've added this as a thread in the 'General'. Going to do that.

**Comment by baughmann** [comment]
@kennyklee General is really more for discussion, this is a specific issue.

I can say I've experienced the same thing sometimes. My wife an I have the same resolution on our monitors, but different make/models. The picker is stretched on hers, but perfect on mine. It's really bizarre.

I thought there was a setting on the `config.plist` to enable/disable HiDPI, but I cannot find it atm. I will look into it again later

**Comment by baughmann** [comment]
Closing for now, feel free to re-open if you need
