### ISSUE TITLE
Random IO Freezes requiring reboot

### ISSUE THREAD

**Issue by baughmann** [baughmann/designaire-z390-intel-i9-9900k-opencore#51]
**Describe the bug**
Seemingly randomly, all IO seems to crash. Anything happening on screen continues to happen, but the system does not play sound or respond to input devices.

**OpenCore Logs**
Thanks to @jirbanas in #48 for the following logs

```
panic(cpu 12 caller 0xffffff80035f9a25): userspace watchdog timeout: no successful checkins from com.apple.logd in 120 seconds
service returned not alive with context : unresponsive dispatch queue(s): com.apple.firehose.io-wl
service: com.apple.logd, total successful checkins since load (4150 seconds ago): 404, last successful checkin: 120 seconds ago
service: com.apple.WindowServer, total successful checkins since load (4120 seconds ago): 412, last successful checkin: 0 seconds ago

Backtrace (CPU 12), Frame : Return Address
0xffffffb948e4b670 : 0xffffff800028e0dd
0xffffffb948e4b6c0 : 0xffffff80003d4f33
0xffffffb948e4b700 : 0xffffff80003c552a
0xffffffb948e4b750 : 0xffffff8000232a2f
0xffffffb948e4b770 : 0xffffff800028d8fd
0xffffffb948e4b890 : 0xffffff800028dbf3
0xffffffb948e4b900 : 0xffffff8000a9d884
0xffffffb948e4b970 : 0xffffff80035f9a25
0xffffffb948e4b980 : 0xffffff80035f9660
0xffffffb948e4b9a0 : 0xffffff8000a1e13e
0xffffffb948e4b9f0 : 0xffffff80035f8a34
0xffffffb948e4bb20 : 0xffffff8000a2837b
0xffffffb948e4bc80 : 0xffffff8000380961
0xffffffb948e4bd90 : 0xffffff800029375d
0xffffffb948e4be00 : 0xffffff8000269cf5
0xffffffb948e4be60 : 0xffffff8000281312
0xffffffb948e4bef0 : 0xffffff80003a982d
0xffffffb948e4bfa0 : 0xffffff8000233216
Kernel Extensions in backtrace:
com.apple.driver.watchdog(1.0)[C29AFC04-7113-39AA-80DF-00F4DDAD0F46]@0xffffff80035f7000->0xffffff80035f9fff

Process name corresponding to current thread: watchdogd
Boot args: alcid=7 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May 8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x0000000000000000
KernelCache base: 0xffffff8000200000
Kernel slide: 0x0000000000010000
Kernel text base: 0xffffff8000210000
__HIB text base: 0xffffff8000100000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4177793830599
Last Sleep: absolute base_tsc base_nano
Uptime : 0x000003ccb7ead1be
Sleep : 0x0000000000000000 0x0000000000000000 0x0000000000000000
Wake : 0x0000000000000000 0x0000000c86793228 0x0000000000000000
```

**Expected behavior**
No freezing

**Screenshots**
N/A

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i9 9900k
 - GPU: AMD Radeon VII
 - Motherboard: Designaire Z390 rev 1.1, BIOS version F9i
 - Storage: Samsung 970 Pro, APFS

**Additional context**
This seems to happen randomly and is experienced by many users. It seems to be a relatively recent phenomena and possibly only occurs when users use Bluetooth IO devices.

So far, it has been experienced by @baughmann @jirbanas @Neolo @idioma

According to [this post on the Apple support forums](https://developer.apple.com/forums/thread/667376?page=6) it appears to happen on real Macs too ever since upgrading to Big Sur.

**Comment by baughmann** [comment]
Well ain't this some shit. I've reset my NVRAM and am trying to get it to crash by using all of my BT accessories... I've got two 4k videos playing as well as Spotify and I just cannot get this machine to freeze... The 4k video idea came from [this forum post](https://forums.macrumors.com/threads/constant-kernel-panics-userspace-watchdog-timeout-no-successful-checkins-from-com-apple-windowserver.2222878/).

**Comment by baughmann** [comment]
Two days later, I have yet to experience the freeze still... knocking on wood over here. I'll consider this fixed after a week without the freezes. Maybe an update to Big Sur or OC requires an NVRAM reset on this system?

**Comment by jiribanas** [comment]
I don’t use the machine over the weekend (work-life balance) but will try the NVRAM reset suggestion on Monday and report back by the end of the week. Last week I got the freeze 9 times so hopefully it’s frequent enough for me to see a difference in just a week after the reset.

**Comment by baughmann** [comment]
@jiribanas All quiet on the eastern front?

**Comment by jiribanas** [comment]
@baughmann Yes, so far so good. No freezes. Even with the MacBook Pro plugged into one of the USB-Cs (this was somehow making the freezing more frequent for me in the past).

**Comment by baughmann** [comment]
@jiribanas Same here... strange. Let's see by the end of the week.

**Comment by hellojere** [comment]
@baughmann I've been experiencing this as well. Had a 2 weeks holiday and now the BIOS has corrupted somehow, so can't boot prior fixing that.

**Comment by baughmann** [comment]
BIOS has corrupted? Weird... Are you sure it isn't the EFI that's corrupted?

**Comment by jiribanas** [comment]
Have been running now nearly 2 weeks after the NVRAM reset, every day for about 10 hours each day, and no IO freeze whatsoever. It looks like the NVRAM reset did the trick.

**Comment by baughmann** [comment]
@jiribanas same here. Let’s consider this temporarily solved. Gonna close the issue but anyone can reopen it again if needed
