### ISSUE TITLE
Not compatible with the Gigabyte Designare Z390 F9j bios update

### ISSUE THREAD

**Issue by kochi** [baughmann/designaire-z390-intel-i9-9900k-opencore#52]
Even disabling new F9j features like "Resizable BAR Support" ended up in random and yet pretty instant freezes.
... from what I've quickly googled, the  F9j bios update should be avoided for hackintoshes (source: tonymacx86 golden builds).

**I've downgraded to bios version F9i, loaded the BIOS_Config 1:1 as provided, used the EFI 1:1 as provided, and I've finally ended up in a smooth running system.**

AFAIK, the F9i bios isn't available on Gigabytes website any more ... I've ended up using this copy: https://www.hackintosh-forum.de/attachment/156892-mb-bios-z390-designare-f9i-zip/ (there are probably plenty of other sources for that F9i bios available).

I don't consider this as a bug or an issue. I just wanted to share my F9j bios update experience ...

Thanks a lot, @baughmann, for all your efforts :)

**Comment by baughmann** [comment]
Maybe related to #51 ? Hard to say. 

Thanks for reporting @kochi 

Don’t thank me, I just made an EFI. All praise goes the OC devs… and random forum people who post helpful stuff lol

**Comment by baughmann** [comment]
Note to self: add F9i bios to this repos releases

**Comment by jiribanas** [comment]
I have a slightly different experience with the F9j BIOS. I've been running on it for over 3 months now. Experiencing freezes #51 with F9i all the way down to F6n. The frequency of freezes didn't get better or worse with F9j. Only the NVRAM reset suggestion in the #51 thread so far seems to be stable but then I had weeks when the freezing didn't happen on F9i and prior BIOS versions too so it's too early to say for sure. My point is, I would not rule out F9j support as yet as it seems to be working fine for at least myself. I have the exact same spec as @baughmann

**Comment by baughmann** [comment]
Any movement on your end @kochi ?

**Comment by kochi** [comment]
@baughmann 

My system is working fine without any freezes for 8 days ...
- Occasionally, my UAD Apollo Solo audio interface doesn't work after wake from sleep (a reboot necessary).
- Sometimes I have to reboot twice to get my UAD Apollo Solo audio interface working (no idea why).
- A had e few cases where I couldn't wake the machine from sleep (reset necessary).

Other remarks ...
- FileVault is activated and working as expected.
- I've updated to 11.5.2 without hassle.
- And last but no least, no freezes at all :)


![Screen Shot 2021-08-13 at 18 45 46](https://user-images.githubusercontent.com/918302/129392717-63743a9e-f27e-48e9-bbfe-5a0aca11fd88.png)

**Comment by baughmann** [comment]
@kochi 
> My system is working fine without any freezes for 8 days ...

Glad to hear it! I still have no idea how to go about

> Sometimes I have to reboot twice to get my UAD Apollo Solo audio interface working (no idea why).

I still don't really know how to go about troubleshooting this :(
