### ISSUE TITLE
Black Screen when installer is charging

### ISSUE THREAD

**Issue by GuitarFa** [baughmann/designaire-z390-intel-i9-9900k-opencore#56]
Hi!
after follow the entire guide, I tried to install the macOS Big Sur, but when I choose the USB installer, the Apple's logo appears during some seconds, and a progress bar starts to advance, but then the screen goes black and nothing else happens.

My specifications are:

CPU | Intel Core i9 9900K
MB | Gigabyte Designare Z390 with F9 BIOS vers.
GPU | GA RX580
STORAGE | Samsung 970 EVO Plus

Any suggestions? Thanks in advanced

**Comment by baughmann** [comment]
Sorry about not responding. Is the issue resolved?

**Comment by GuitarFa** [comment]
Don't worry, I was not able to get it with Big Sur, but I created a new installation usb with Monterey and I got it.
Thank you!
