### ISSUE TITLE
Thunderbolt 3 ports only work at USB 3.1 speeds

### ISSUE THREAD

**Issue by hypajumpa** [baughmann/designaire-z390-intel-i9-9900k-opencore#8]
Hi Nick,
I have the exact same hardware (i9 9900k, Z390 Designare, Fenvi T 919, Radeon RX580) with you except the Graphics card which is a Radeon RX5 580. 
I've recently installed Catalina using Opencore 0.6.0 everything seems to be working except Thunderbolt, which is the whole point of this build.
I followed the Opencore guide and created my custom SSDT's in windows and also tried to create my custom USBPorts.kext I used USBInjectall.kext with the needed patches but couldn't get it to find my SSP01 & SSP02 ports which are the same ports which Thunderbolt uses.
Then I tried your EFI folder with no luck, I also checked the info.plist in your USBPorts.kext and it doesn't seem to be configured at all HS11 and HS12 seems to be using USB3 ports and  SSP01 and SSP02 ports don't even show up. Did you check with hackintool or IORegistryexplorer if you those two ports are recognised and active in your system? I'm not sure actually if they need to be configured in order to Thunderbolt to be working. 
I've also tried some other user's efi folder which had more SSDT's in his ACPI folder for the thunderbolt and when I boot with that, SSP01 and SSP02 ports did show up but as a part of the XHC5 bus.  I'm not sure how to proceed, do you have a suggestion?

**Comment by baughmann** [comment]
Hey hypa,

Thanks for the issue. Actually, both of my TB3 ports seem to be working just fine, including hotswapping. I just tested it again right before typing this up.

You can take a look at my ports [in my response to this closed issue](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/issues/3#issuecomment-668907015). I'm actually not using `SSP01` nor `SSP02`, and all of my IO ports are tested working :/

Can you go ahead and wipe a USB drive and throw my EFI on there and boot from there just so we can make sure we have a fresh try? I'm not OC expert, but I suppose that maybe one of your kexts or ACPI patches might be hanging on somehow...

**Comment by hypajumpa** [comment]
Sure I can do it, I'm on windows now to update the Thunderbolt firmware with the link below, but maybe I shouldn't in order to be synced with you, have you done anything like that? Firmware update, I also read that some people are flashing the thunderbolt rom in order to get it work so I'm really confused.

https://www.gigabyte.com/Motherboard/GC-TITAN-RIDGE-rev-10/support#support-dl-utility
I don't know if it's going to help but

**Comment by hypajumpa** [comment]
Turns out to be that update is for add in cards or maybe I'm missing some software. Switching to OSX now, I'll post some screenshots.

**Comment by hypajumpa** [comment]
Here are some screenshots from my current state.
![Screen Shot 2020-08-14 at 02 58 33](https://user-images.githubusercontent.com/68965607/90198603-cbcc6300-ddda-11ea-8a0c-32737da639a2.png)
![Screen Shot 2020-08-14 at 02 51 04](https://user-images.githubusercontent.com/68965607/90198612-d0911700-ddda-11ea-8f6f-a1693d46d0b2.png)
![Screen Shot 2020-08-14 at 02 49 30](https://user-images.githubusercontent.com/68965607/90198616-d2f37100-ddda-11ea-8a6d-e1d38b12a4a4.png)

**Comment by hypajumpa** [comment]
I booted with your EFI folder now and here are the same screenshots.
![Screen Shot 2020-08-14 at 03 10 46](https://user-images.githubusercontent.com/68965607/90198987-126e8d00-dddc-11ea-8f44-d9eedbd646ac.png)
![Screen Shot 2020-08-14 at 03 11 07](https://user-images.githubusercontent.com/68965607/90199018-24e8c680-dddc-11ea-8444-f2e5f7cc1de1.png)
![Screen Shot 2020-08-14 at 03 11 56](https://user-images.githubusercontent.com/68965607/90199024-29ad7a80-dddc-11ea-9db0-3bf8515fbf37.png)

**Comment by baughmann** [comment]
Honestly the only thing I've done is kept my BIOS up-to-date (currently on a pre-release version, though), and any updates that pop into the queue on Windows Update. I would definitely recommend updating your drivers to the latest though. Probably check the Device Manager in Windows to see when they were updated.

What tool did you use to get the IOService screenshot? I know I've seen it before but I think the last time I did was when I was originally building this EFI, and I don't remember what it is...

SS03 is my top USB-C port and SS04 is my lower-one. Neither one of yours is showing as active.

I noticed it appears that you have some PCIe TB3 cards. Just to clarify, neither those *nor* the built-in ones are working, right? No worries about the empty PCI and TB screens in System Information. Same thing here, and across 99% of Hackintoshes AFAIK.

What's your BIOS look like? If you recently flashed it to update it, *most* settings will be reverted to factory. Found that one out the hard way...

**Comment by baughmann** [comment]
FYSA, as long as we're swapping screenshots, here are two. One with my lower and one with my upper TB3 ports in use.

<img width="873" alt="Screen Shot 2020-08-13 at 8 18 47 PM" src="https://user-images.githubusercontent.com/6177411/90199536-1336fd00-dda3-11ea-9e8e-2b27fbd67760.png">
<img width="874" alt="Screen Shot 2020-08-13 at 8 16 22 PM" src="https://user-images.githubusercontent.com/6177411/90199537-1500c080-dda3-11ea-9a66-f76ba6d8df3a.png">

**Comment by hypajumpa** [comment]
Actually I do have the SS03 but not the SS04, I must have missed that.

I referred to this while I was creating it seems to be correct;
https://www.hackintosh-forum.de/attachment/120767-z390-designare-usb-ports-pdf/

**Comment by baughmann** [comment]
Yeah maybe you grabbed the wrong screenshot or something? The one I looked at showed both the USB-C and USB3 SS)3 and SS04 ports not active: 

You know I remember seeing that PDF when I was making the kexts and ACPI patches as well. I will actually probably add that PDF to this repo in for safe keeping.

You will notice that both the HS13 and HS07 ports show in use when the corresponding SS0X port does in the screenshots I provided.

That leads me to the next check that we shoudl double-check: the BIOS. What firmware version are you running, and what are your IO and TB3 settings?

<img width="406" alt="Screen Shot 2020-08-13 at 8 35 12 PM" src="https://user-images.githubusercontent.com/6177411/90200098-a15fb300-dda4-11ea-92b4-053cc8698918.png">

**Comment by hypajumpa** [comment]
I'll send the BIOS settings but the hardware you connect is actually recognized as a USB 3.0 Hub? It seems to be connected via Type-C connector but maybe you're using the hub with USB 3.0 protocol/speed? It seems like a multi-protocol HUB depending on the items you connect because it's also recognized as a USB 2.0 Hubon HS13 & HS08.
Do you have any thunderbolt devices connected to the hub?

**Comment by hypajumpa** [comment]
The software you asked is IORegistry Explorer here's the link.
https://mac.softpedia.com/get/System-Utilities/IORegistryExplorer.shtml

**Comment by baughmann** [comment]
Yes, sorry I should have clarified. I am using a 4-port USB 3.0 Hub that is connected via USB-C. I think I might have a USB-C cable I could use to plug in and Android phone around here. I'll see if I can find it.

**Comment by hypajumpa** [comment]
Yes but that still doesn't mean that Thunderbolt will work, as far as I know although Thunderbolt 3 and USB 3.1 uses the same Type-C connector their controllers and drivers are different. I think the Android phones will also use USB 3.1 not TB.
You should check it with a thunderbolt device like a thunderbolt hard disk or a sound card like Apollo which is my case.

**Comment by hypajumpa** [comment]
My BIOS is F9b and the thunderbolt configs are like this

![IMG_6595](https://user-images.githubusercontent.com/68965607/90201724-67ae9c80-dde4-11ea-89c2-e33c790ff325.jpg)
![IMG_0458](https://user-images.githubusercontent.com/68965607/90201737-6e3d1400-dde4-11ea-937e-f3b1275f70d0.jpg)
![IMG_1074](https://user-images.githubusercontent.com/68965607/90201738-71d09b00-dde4-11ea-9d80-d9d7bcbf37a6.jpg)

**Comment by baughmann** [comment]
Hmm that’s a good point. The Hackintool screenshots also show the same speed for both the front IO and for the USB-C hub connections.

I don’t have any native TB3 devices here. Any way you know of to check the protocol in use on a device plugged into the TB3 port? If not, do you know of a cheap TB3 native device I could buy on Amazon or something so that we’re on the same page?

My BIOS is currently F9h and *slightly* different configurations but nothing that should make any difference

**Comment by hypajumpa** [comment]
I don't know any other TB devices other than the audio interfaces and hdd which aren't really cheap :)
I don't know if it's ok to post links to other forums on GitHub but there's a lot going on about Thunderbolt and Z390 designare, they say that there are 3 different firmware versions of TB chipset 23, 33 and 43. And 43 seems to be the latest and problematic. Also to enable Thunderbolt Local node a rom flash is needed. 
There are some clover efis which are told  to be working but I want to stay in OC.

**Comment by clichequiche** [comment]
Can't seem to get TB working with your EFI on a similar setup either (Designare Z390, i7 9700, Radeon RX560, BIOS v F9g).

TB device is a UAD Apollo Twin X Duo

**Comment by hypajumpa** [comment]
good news is that today i finally made it happen, apollo is connected and working, haven't tested it with pro tools or logic yet but seems to be working fine.
I don't know if it's ok to give links to the other forums here, but I found a very clean and fully working Opencore 0.6.0 EFI Folder.

**Comment by baughmann** [comment]
Please post it! I’ll go through there myself and see if I can adapt my own EFI better

**Comment by hypajumpa** [comment]
Here it is with many thanks to CaseySJ, 

https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/post-2158315

It's important to boot with a USB stick first as it's described, I entered the SMBIOS settings in the config.plist with OpenCore configurator also I did reset the NVRAM and unlocked MSR 0xE2 (CFG-Lock) as described in this post before booting.

Also before connecting the apollo I installed the UAD software first granting access to all the requests of Catalina, then I followed these instructions, it looks a bit supersticious but it worked :)

https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/post-2065252

**Comment by clichequiche** [comment]
Ah, CaseySJ's build worked for me too. I'm able to hotplug my UAD Apollo Twin X DUO no problem

**Comment by baughmann** [comment]
Closing for now. I will need to integrate some of CaseySJ's EFI into my own.

**Comment by baughmann** [comment]
Hey @hypajumpa did you use the [OpenCore](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-2424#post-2158315) version of CaseySJ's EFI, or the Clover version?

**Comment by hypajumpa** [comment]
Hi Nick,

Opencore version 0.6.2 at the moment but i had an issue with the Pulse
Radeon RX 580,
it’s not even recognised even at the BIOS, maybe it’s a hardware issue, but
i can still use it with the onboard iGPU .

**Comment by baughmann** [comment]
I would check and see if there's a newer BIOS version, and also boot to Windows and update the GPU drivers
