### ISSUE TITLE
Hangs at apple logo

### ISSUE THREAD

**Issue by EELinneman** [baughmann/designaire-z390-intel-i9-9900k-opencore#9]
I have the same setup as you except a 5700 XT video card.  Same board, chip and ssd.  Modified the SMBIOS ID values and when booting, it hangs at the apple logo and the start of the progress bar.

**Comment by baughmann** [comment]
Do you have your OpenCore logs?

**Comment by EELinneman** [comment]
I'll pull these.  Got a job interview in a couple of minutes!

**Comment by baughmann** [comment]
Good luck! Post them when you can.

**Comment by baughmann** [comment]
@EELinneman Closing this for now. Feel free to re-open if you continue to have problems.
